<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Payout Statement</title>
<style>
  body { font-family: DejaVu Sans, sans-serif; font-size: 13px; color: #111; margin: 0; padding: 32px; }
  .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 32px; border-bottom: 2px solid #7C3AED; padding-bottom: 20px; }
  .brand { font-size: 22px; font-weight: bold; color: #7C3AED; }
  .brand-sub { font-size: 12px; color: #666; margin-top: 2px; }
  .doc-title { font-size: 14px; font-weight: bold; text-align: right; }
  .doc-meta { font-size: 11px; color: #666; text-align: right; margin-top: 4px; }
  .section { margin-bottom: 24px; }
  .section-title { font-size: 11px; font-weight: bold; text-transform: uppercase; letter-spacing: .08em; color: #7C3AED; margin-bottom: 8px; }
  table { width: 100%; border-collapse: collapse; }
  th { text-align: left; font-size: 11px; font-weight: bold; text-transform: uppercase; letter-spacing: .06em; color: #666; padding: 6px 10px; background: #f5f3ff; border-bottom: 1px solid #ddd; }
  td { padding: 8px 10px; border-bottom: 1px solid #eee; vertical-align: top; }
  .amount { text-align: right; font-variant-numeric: tabular-nums; }
  .total-row td { font-weight: bold; background: #f5f3ff; font-size: 14px; }
  .deduction { color: #dc2626; }
  .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #ddd; font-size: 11px; color: #999; text-align: center; }
  .pill { display: inline-block; padding: 2px 8px; border-radius: 99px; font-size: 11px; font-weight: bold; }
  .pill-success { background: #dcfce7; color: #166534; }
  .pill-pending { background: #fef9c3; color: #854d0e; }
</style>
</head>
<body>

<div class="header">
  <div>
    <div class="brand">{{ config('app.name', 'VortexOps') }}</div>
    <div class="brand-sub">Payout Statement</div>
  </div>
  <div>
    <div class="doc-title">Streamer Payout</div>
    <div class="doc-meta">Generated {{ now()->format('M j, Y') }}</div>
  </div>
</div>

<div class="section">
  <div class="section-title">Show Details</div>
  <table>
    <tr>
      <td style="width:50%"><strong>Show</strong><br>{{ $payout->show?->title ?? '—' }}</td>
      <td><strong>Date</strong><br>{{ $payout->show?->show_date?->format('F j, Y') ?? '—' }}</td>
    </tr>
    <tr>
      <td><strong>Streamer</strong><br>{{ $payout->streamer?->name ?? '—' }}</td>
      <td><strong>Payout Type</strong><br>{{ ucfirst(str_replace('_', ' ', $payout->payout_type)) }}</td>
    </tr>
    @if($payout->routing_bank_label)
    <tr>
      <td colspan="2"><strong>Routing / Bank Label</strong><br>{{ $payout->routing_bank_label }}</td>
    </tr>
    @endif
  </table>
</div>

<div class="section">
  <div class="section-title">Earnings Breakdown</div>
  <table>
    <thead>
      <tr><th>Description</th><th class="amount">Amount</th></tr>
    </thead>
    <tbody>
      @if((float)$payout->base_pay)
      <tr><td>Base Pay</td><td class="amount">${{ number_format($payout->base_pay, 2) }}</td></tr>
      @endif
      @if((float)$payout->tips_pay)
      <tr><td>Tips</td><td class="amount">${{ number_format($payout->tips_pay, 2) }}</td></tr>
      @endif
      @if((float)$payout->deductions_total)
      <tr><td class="deduction">Deductions</td><td class="amount deduction">−${{ number_format($payout->deductions_total, 2) }}</td></tr>
      @endif
      @if($payout->notes)
      <tr><td colspan="2" style="font-size:11px;color:#666;padding-top:4px">Note: {{ $payout->notes }}</td></tr>
      @endif
    </tbody>
    <tfoot>
      <tr class="total-row">
        <td>Net Pay</td>
        <td class="amount">${{ number_format($payout->net_pay, 2) }}</td>
      </tr>
    </tfoot>
  </table>
</div>

@if($payout->show && (float)$payout->show->gross_revenue)
<div class="section">
  <div class="section-title">Show Performance</div>
  <table>
    <tr>
      <td style="width:33%"><strong>Gross Revenue</strong><br>${{ number_format($payout->show->gross_revenue, 2) }}</td>
      <td style="width:33%"><strong>Units Sold</strong><br>{{ $payout->show->units_sold ?? '—' }}</td>
      <td><strong>Buyers</strong><br>{{ $payout->show->buyers_count ?? '—' }}</td>
    </tr>
  </table>
</div>
@endif

<div class="footer">
  This statement was generated by {{ config('app.name', 'VortexOps') }} on {{ now()->format('M j, Y \a\t g:i A') }}.
  Contact your show coordinator with any questions.
</div>

</body>
</html>
