<x-filament-panels::page>
<style>
@media(max-width:640px){
  body:has(.vx-inventory-list) .fi-page-header{display:none!important}.vx-inventory-desktop-tools,.vx-inventory-kpis{display:none!important}.vx-inventory-items-panel{border:0!important;background:transparent!important;box-shadow:none!important}.vx-inventory-items-panel>div{padding:0!important}
  body:has(.vx-inventory-list) nav.fi-topbar{background:rgba(7,12,22,.96)!important;border-bottom:1px solid rgba(255,255,255,.06)!important;backdrop-filter:blur(18px);box-shadow:none!important}
  body:has(.vx-inventory-list) nav.fi-topbar svg{color:#e8e8f0!important}body:has(.vx-inventory-list) nav.fi-topbar .fi-icon-btn:hover{background:rgba(124,58,237,.18)!important}
  body:has(.vx-inventory-list) .fi-modal-window{border:1px solid rgba(255,255,255,.1)!important;border-radius:28px 28px 0 0!important;background:#10151f!important;box-shadow:0 -20px 70px rgba(0,0,0,.5)!important}
  body:has(.vx-inventory-list) .fi-modal-header{border-bottom:1px solid rgba(255,255,255,.06)!important;background:transparent!important}.dark .vx-inventory-mobile-intro{color:#fff}
  body:has(.vx-inventory-list) .fi-ta{background:transparent!important}body:has(.vx-inventory-list) .fi-ta-ctn{border-radius:16px!important;border-color:rgba(255,255,255,.09)!important;overflow:hidden!important}
  body:has(.vx-inventory-list) .fi-ta-row{border-bottom:1px solid rgba(255,255,255,.07)!important}body:has(.vx-inventory-list) .fi-ta-header-toolbar{padding:12px 0!important;gap:10px!important}
  body:has(.vx-inventory-list) .fi-ta-search-field{min-width:0!important;flex:1!important}body:has(.vx-inventory-list) .fi-ta-filters-trigger{border:1px solid rgb(124 58 237)!important;border-radius:10px!important;color:#c4b5fd!important}
}
</style>
<div x-data x-on:barcode-scanned.window="if ($wire.barcodeScanTargetId) $wire.saveScannedBarcode($event.detail.value)"></div>
<div class="space-y-3 sm:space-y-5 vx-inventory-list" data-vx-page="inventory-center">
    <div class="vx-inventory-mobile-intro sm:hidden"><h2 class="text-2xl font-bold text-gray-950 dark:text-white">Inventory</h2><p class="mt-1 text-sm text-gray-500">Track and manage your inventory items.</p></div>
    <section class="vx-inventory-desktop-tools overflow-hidden rounded-xl border border-gray-200 bg-white dark:border-gray-700 dark:bg-gray-900 sm:rounded-2xl"><div class="p-4 sm:p-5"><div class="text-[10px] font-bold uppercase tracking-[.12em] text-primary-600 sm:text-xs">Inventory Center</div><h2 class="mt-1 text-lg font-semibold sm:text-xl">What are you trying to do?</h2><p class="mt-1 text-xs text-gray-500 sm:text-sm">Search first when checking stock. Scan, add, receive, or manage locations from here.</p></div><div class="grid grid-cols-2 gap-px bg-gray-100 dark:bg-gray-800 sm:grid-cols-4">@php $user=auth()->user();$canReceive=$user?->isAdmin()||$user?->isOwner();@endphp<a href="{{\App\Filament\Resources\InventoryItemResource::getUrl('quick-add')}}" class="bg-white p-3 dark:bg-gray-900 sm:p-4"><x-heroicon-o-bolt class="h-5 w-5 text-primary-600"/><div class="mt-2 text-sm font-semibold">Quick Add</div></a>@if($canReceive)<a href="{{\App\Filament\Pages\InventoryScanner::getUrl()}}" class="bg-white p-3 dark:bg-gray-900 sm:p-4"><x-heroicon-o-qr-code class="h-5 w-5 text-primary-600"/><div class="mt-2 text-sm font-semibold">Quick Scan</div></a><a href="{{\App\Filament\Resources\PalletResource::getUrl('index')}}" class="bg-white p-3 dark:bg-gray-900 sm:p-4"><x-heroicon-o-inbox-arrow-down class="h-5 w-5 text-primary-600"/><div class="mt-2 text-sm font-semibold">Receive Shipment</div></a>@endif<a href="{{\App\Filament\Resources\InventoryLocationResource::getUrl('index')}}" class="bg-white p-3 dark:bg-gray-900 sm:p-4"><x-heroicon-o-map-pin class="h-5 w-5 text-primary-600"/><div class="mt-2 text-sm font-semibold">Locations</div></a></div></section>
    <div class="vx-inventory-kpis"><x-kpi-row :stats="$this->getStats()" /></div>
    <section class="vx-inventory-items-panel overflow-hidden rounded-xl border border-gray-200 bg-white dark:border-gray-700 dark:bg-gray-900 sm:rounded-2xl"><div class="hidden border-b border-gray-100 px-5 py-3 dark:border-gray-800 sm:block"><h2 class="text-base font-semibold">Inventory Items</h2><p class="mt-0.5 text-xs text-gray-500">Search by item name, SKU, or barcode.</p></div><div class="p-1 sm:p-2">{{$this->table}}</div></section>
</div>
</x-filament-panels::page>
