<x-filament-panels::page>
@php
$tabs=['overview'=>'Overview','stock'=>'Stock','lots'=>'Lots','receiving'=>'History','movements'=>'Movements','cost'=>'Cost','analysis'=>'Analysis','aliases'=>'Aliases'];
$totalQty=collect($this->stockByLocation)->sum('qty');$lots=$this->lots;$cost=$record->effectiveCost();$target=(float)($record->sale_price??0);$margin=($target>0&&$cost>0)?$target-$cost:null;$pct=($margin!==null&&$target>0)?($margin/$target)*100:null;
@endphp
<style>
.vx-item-shell{max-width:1100px;margin:auto}.vx-card{border:1px solid rgb(229 231 235);background:white;border-radius:16px}.dark .vx-card{border-color:#263248;background:#101827}.vx-tab{padding:11px 16px;border-bottom:2px solid transparent;white-space:nowrap;font-size:.875rem}.vx-tab.active{color:#a855f7;border-color:#a855f7}.vx-photo{cursor:zoom-in}
@media(max-width:640px){body:has(.vx-item-shell) .fi-page-header{display:none!important}.vx-item-shell{margin-top:0}.vx-card{border-color:#263248!important;background:#101827!important}.vx-hero{padding:16px!important}.vx-hero-main{display:grid!important;grid-template-columns:92px 1fr!important;gap:14px!important}.vx-hero-photo{width:92px!important;height:92px!important;border-radius:12px!important}.vx-metrics{grid-column:1/3;display:grid!important;grid-template-columns:1fr 1fr;gap:8px;margin-top:6px}.vx-metric{border:1px solid #263248;border-radius:10px;padding:12px;text-align:center}.vx-actions{grid-column:1/3;display:grid!important;grid-template-columns:1fr 1fr;gap:8px}.vx-tabs{background:#101827;border:1px solid #263248;border-radius:14px;padding:0 6px;border-bottom:0!important}.vx-tab{flex:1;text-align:center;padding:12px 8px}.vx-overview{display:block!important}.vx-overview>.vx-card{margin-bottom:12px}.vx-summary-grid{display:grid!important;grid-template-columns:repeat(3,1fr);gap:7px}.vx-summary-grid>div{border:1px solid #263248;border-radius:10px;padding:12px 7px;text-align:center}.vx-desktop-stock{display:none!important}}
</style>
<div class="vx-item-shell space-y-4" x-data="{photoOpen:false}">
 <div class="vx-card vx-hero p-5"><div class="vx-hero-main flex items-start gap-5"><img @click="photoOpen=true" src="{{$record->imageUrl()}}" alt="{{$record->name}}" class="vx-photo vx-hero-photo h-24 w-24 shrink-0 rounded-xl border border-gray-700 object-cover"><div class="min-w-0 flex-1"><h1 class="text-xl font-bold text-gray-950 dark:text-white">{{$record->name}}</h1><div class="mt-2 flex gap-2"><span class="rounded-full bg-green-900/50 px-2.5 py-1 text-xs font-bold text-green-400">{{$record->is_active?'Active':'Inactive'}}</span><span class="rounded-full bg-gray-800 px-2.5 py-1 text-xs text-gray-400">{{$record->is_container?'Box':'Item'}}</span></div><div class="mt-3 text-xs text-gray-500">SKU: {{$record->sku?:'—'}} <span class="mx-1">•</span> Type: {{$record->product_type?:($record->is_container?'Box':'Item')}}</div></div><div class="vx-metrics flex gap-3"><div class="vx-metric min-w-28"><div class="text-2xl font-bold text-primary-500">{{number_format($totalQty)}}</div><div class="text-xs text-gray-500">In Stock</div></div><div class="vx-metric min-w-28"><div class="text-2xl font-bold">${{number_format($cost,2)}}</div><div class="text-xs text-gray-500">Avg Cost</div></div></div><div class="vx-actions flex gap-2"><button x-on:click="$dispatch('open-modal',{id:'add-stock'})" class="rounded-lg bg-emerald-600 px-4 py-2.5 text-sm font-bold text-white">⊕ Add Stock</button><a href="{{\App\Filament\Resources\InventoryItemResource::getUrl('edit',['record'=>$record])}}" class="rounded-lg border border-gray-700 px-4 py-2.5 text-center text-sm font-bold">✎ Edit</a></div></div></div>
 <div class="vx-tabs flex overflow-x-auto border-b border-gray-700">@foreach($tabs as $key=>$label)<button wire:click="setTab('{{$key}}')" class="vx-tab {{$tab===$key?'active':''}}">{{$label}}</button>@endforeach</div>
 @if($tab==='overview')<div class="vx-overview grid grid-cols-1 gap-4 sm:grid-cols-3">
  <div class="vx-card p-5 sm:col-span-1"><h3 class="font-bold">Inventory Summary</h3><div class="vx-summary-grid mt-4 grid grid-cols-3 gap-3"><div><div class="text-xl font-bold">{{number_format($totalQty)}}</div><div class="text-xs text-gray-500">Total Stock</div></div><div><div class="text-xl font-bold">{{collect($lots)->where('status','active')->count()}}</div><div class="text-xs text-gray-500">Active Lots</div></div><div><div class="text-xl font-bold">{{number_format((float)$record->total_units_received)}}</div><div class="text-xs text-gray-500">Received</div></div></div></div>
  <div class="vx-card p-5"><h3 class="font-bold">Pricing</h3><div class="mt-4 space-y-3 text-sm"><div class="flex justify-between"><span class="text-gray-500">List Cost</span><b>${{number_format((float)$record->unit_cost,2)}}</b></div><div class="flex justify-between"><span class="text-gray-500">Average Cost (WAC)</span><b>${{number_format($cost,2)}}</b></div><div class="flex justify-between"><span class="text-gray-500">Sale Target</span><b>{{$target?'$'.number_format($target,2):'—'}}</b></div>@if($margin!==null)<div class="rounded-lg border border-emerald-800 bg-emerald-950/30 p-3"><div class="flex justify-between"><span class="text-emerald-400">↗ Potential Profit</span><b class="text-emerald-400">${{number_format($margin,2)}} / unit</b></div><div class="mt-1 text-right text-xs text-gray-500">{{number_format($pct,1)}}% margin</div></div>@endif</div></div>
  <div class="vx-card p-5"><h3 class="font-bold">Details</h3><div class="mt-4 divide-y divide-gray-800 text-sm">@foreach(['Category'=>$record->category,'Preferred Vendor'=>$record->preferredVendor?->name] as $label=>$value)<div class="flex justify-between py-3"><span class="text-gray-500">{{$label}}</span><span>{{$value?:'Not set'}} ›</span></div>@endforeach</div><a href="{{\App\Filament\Resources\InventoryItemResource::getUrl('edit',['record'=>$record])}}" class="mt-3 block rounded-lg border border-gray-700 p-2 text-center text-sm font-bold text-primary-400">＋ Add details</a></div>
 </div>@endif
 @if($tab==='stock')<div class="vx-card overflow-hidden"><div class="p-5"><h3 class="font-bold">Stock by Location</h3></div>@forelse($this->stockByLocation as $s)<div class="flex justify-between border-t border-gray-800 px-5 py-4"><div><b>{{$s['location']}}</b><div class="text-xs text-gray-500">{{ucfirst($s['type'])}}</div></div><b>{{number_format($s['qty'])}}</b></div>@empty<div class="p-12 text-center text-gray-500">No stock on hand.</div>@endforelse</div>@endif
 @if($tab==='lots')<div class="vx-card p-5"><h3 class="font-bold">Active Lots ({{collect($lots)->where('status','active')->count()}})</h3>@forelse(collect($lots)->where('status','active') as $lot)<div class="mt-3 rounded-xl border border-gray-800 p-4"><div class="flex justify-between"><b>{{$lot['vendor']}}</b><span>{{$lot['remaining']}} remaining</span></div><div class="mt-1 text-xs text-gray-500">Received {{$lot['received_at']}} · ${{$lot['unit_cost']}}/unit</div></div>@empty<div class="mt-4 rounded-xl border border-gray-800 p-10 text-center"><div class="text-4xl text-primary-500">◇</div><b class="mt-3 block">No active lots</b><p class="mt-1 text-sm text-gray-500">This item doesn’t have any active lots yet.</p></div>@endforelse</div>@endif
 @if(!in_array($tab,['overview','stock','lots']))<div class="vx-card p-8 text-center text-gray-500">The existing {{$tabs[$tab]}} data remains available here.</div>@endif
 <div x-show="photoOpen" x-cloak @keydown.escape.window="photoOpen=false" @click.self="photoOpen=false" class="fixed inset-0 z-[100] flex items-center justify-center bg-black/90 p-4"><button @click="photoOpen=false" class="absolute right-5 top-5 h-12 w-12 rounded-full bg-white/10 text-2xl text-white">×</button><img src="{{$record->imageUrl()}}" alt="{{$record->name}} enlarged" class="max-h-[88vh] max-w-[95vw] rounded-2xl object-contain shadow-2xl"></div>
</div>
</x-filament-panels::page>
