import { test, expect } from '@playwright/test';
import fs from 'node:fs';
test('shared mobile controls preserve bindings, keyboard access and list pages', async ({ page }) => {
    await page.setViewportSize({width:390,height:844});
    await page.setContent('<main class="fi-main"><label>Location<select id="location"><option value="">All Locations</option><option value="1">Warehouse</option><option value="2">Brandon</option></select></label><div data-vx-mobile-page>'+Array.from({length:12},(_,i)=>'<article>Item '+i+'</article>').join('')+'</div></main>');
    await page.addStyleTag({content:fs.readFileSync('resources/css/mobile-controls.css','utf8')});
    await page.evaluate(() => { (window as any).changes=0; document.querySelector('select')!.addEventListener('change',()=>{(window as any).changes++;}); });
    await page.addScriptTag({content:fs.readFileSync('resources/js/mobile-controls.js','utf8').replace(/^import .*;\n/,'')});
    await page.getByRole('button',{name:'Location: All Locations',exact:true}).click();
    await expect(page.getByRole('dialog',{name:'Location',exact:true})).toBeVisible();
    await page.getByRole('searchbox').fill('bran');
    await expect(page.getByRole('button',{name:'Warehouse',exact:true})).toHaveCount(0);
    await page.getByRole('button',{name:'Brandon',exact:true}).click();
    await expect(page.locator('#location')).toHaveValue('2');
    expect(await page.evaluate(()=>(window as any).changes)).toBe(1);
    await page.getByRole('button',{name:'Location: Brandon',exact:true}).click();
    await page.getByRole('searchbox').press('Escape');
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await expect(page.getByRole('button',{name:'Location: Brandon',exact:true})).toBeFocused();
    await expect(page.locator('article:visible')).toHaveCount(5);
    await page.getByRole('button',{name:'Next',exact:true}).click();
    await expect(page.locator('article:visible')).toHaveCount(5);
    await page.getByRole('button',{name:'Next',exact:true}).click();
    await expect(page.locator('article:visible')).toHaveCount(2);
    await expect(page.getByRole('button',{name:'Next',exact:true})).toBeDisabled();
    await page.setViewportSize({width:1440,height:900});
    await expect(page.locator('article:visible')).toHaveCount(12);
    await expect(page.locator('#location')).toBeVisible();
    await expect(page.locator('.vx-picker-trigger')).toBeHidden();
});
