from pathlib import Path
p=Path('scripts/whatnot-scraper.cjs')
s=p.read_text()
s=s.replace("const SWITCH_ROLE_SEL = 'div.eCoev h4.ogVNN';", "const SWITCH_ROLE_SEL = '#team-invite-switch-role-anchor, div.eCoev h4.ogVNN';", 1)
s=s.replace("    'img[alt=\"avatar\"]',", "    'img.z-avatar-image[alt][width=\"40\"][height=\"40\"]',\n    'img[alt=\"avatar\"]',", 1)
old='''  const SWITCH_ROLE_BUTTON_SEL = 'button[formaction="/api/v1/auth/switch-role"]';\n  const targetKey = channelName.replace(/[^a-z0-9]/gi, '').toLowerCase();\n\n  let target = null;\n  const roleButtons = await page.$$(SWITCH_ROLE_BUTTON_SEL).catch(() => []);\n  for (const btn of roleButtons) {\n    const btnText = await btn.innerText().catch(() => '');\n    if (btnText.replace(/[^a-z0-9]/gi, '').toLowerCase().includes(targetKey)) {\n      info(`switchToChannel: found channel option matching "${channelName}" (button text: ${btnText.replace(/\\s+/g, ' ').trim()})`);\n      target = btn;\n      break;\n    }\n  }\n'''
new='''  const SWITCH_ROLE_BUTTON_SEL = 'button[formaction="/api/v1/auth/switch-role"]';\n  const targetKey = channelName.replace(/[^a-z0-9]/gi, '').toLowerCase();\n\n  let target = null;\n  const exactAvatar = page.locator(`button:has(img.z-avatar-image[alt="${channelName.toLowerCase()}"])`).first();\n  if (await exactAvatar.isVisible().catch(() => false)) {\n    info(`switchToChannel: found exact role button by avatar alt="${channelName.toLowerCase()}"`);\n    target = exactAvatar;\n  }\n\n  if (!target) {\n    const roleButtons = await page.$$(SWITCH_ROLE_BUTTON_SEL).catch(() => []);\n    for (const btn of roleButtons) {\n      const btnText = await btn.innerText().catch(() => '');\n      if (btnText.replace(/[^a-z0-9]/gi, '').toLowerCase().includes(targetKey)) {\n        info(`switchToChannel: found channel option matching "${channelName}" (button text: ${btnText.replace(/\\s+/g, ' ').trim()})`);\n        target = btn;\n        break;\n      }\n    }\n  }\n'''
if old not in s: raise SystemExit('target role block not found')
s=s.replace(old,new,1)
old2='''async function getActiveChannelUsername(page) {\n  // Prefer identity links in seller navigation, but do not require the visible\n'''
new2='''async function getActiveChannelUsername(page) {\n  const currentRole = page.locator('button:has(svg[aria-label="Current account"]) img.z-avatar-image[alt]').first();\n  const currentRoleAlt = await currentRole.getAttribute('alt', { timeout: 1000 }).catch(() => null);\n  if (currentRoleAlt) return currentRoleAlt;\n\n  const visibleAvatars = page.locator('img.z-avatar-image[alt][width="40"][height="40"]:visible');\n  const visibleAvatarCount = Math.min(await visibleAvatars.count().catch(() => 0), 10);\n  if (visibleAvatarCount === 1) {\n    const alt = await visibleAvatars.first().getAttribute('alt', { timeout: 1000 }).catch(() => null);\n    if (alt) return alt;\n  }\n\n  // Prefer identity links in seller navigation, but do not require the visible\n'''
if old2 not in s: raise SystemExit('active function block not found')
s=s.replace(old2,new2,1)
p.write_text(s)
