<x-filament-panels::page>
@php
    $show = $this->record;
    $show->loadMissing(['streamers','channel','fulfillmentUsers','streamerLogEntry.streamer','shipments','payouts.batch','latestDeductionRequest.lines.inventoryItem']);
    $pnl = $show->profitAndLoss();
    $workflow = app(\App\Services\ShowWorkflowService::class)->stateFor($show);
    $workflowKey = $workflow['key'] ?? 'show';
    $report = $show->streamerLogEntry;
    $shipments = $show->shipments;
    $payouts = $show->payouts;
    $deliveredShipments = $shipments->filter(fn ($shipment) => strtolower((string) $shipment->status) === 'delivered')->count();
    $openShipments = max(0, $shipments->count() - $deliveredShipments);
    $analyticsMissing = $show->show_date?->lte(today()) && !in_array($show->status,['cancelled'],true) && (float)$show->gross_revenue===0.0 && (float)$show->whatnot_net===0.0;
    $reportLabel = match(true) {
        $report?->approval_status === 'approved' || $report?->status === 'admin_approved' => 'Approved',
        $report?->status === 'changes_requested' || $report?->approval_status === 'rejected' => 'Changes Requested',
        (bool)$report?->submitted_at => 'Submitted',
        (bool)$report => 'Draft',
        default => 'Not Started',
    };
    $workflowSteps = ['show'=>'Show','streamer_log'=>'Streamer Report','admin_review'=>'Admin Review','fulfillment'=>'Fulfillment','payroll_review'=>'Payroll Review','payroll_ready'=>'Payroll Ready','payroll'=>'Pay Run','paid'=>'Paid'];
    $stepKeys = array_keys($workflowSteps);
    $currentStep = array_search($workflowKey,$stepKeys,true);
    $currentStep = $currentStep===false?0:$currentStep;
    $primary = match($workflowKey) {
        'streamer_log' => ['label'=>$report?->status==='changes_requested'?'Fix Show Report':($report?'Open Show Report':'Start Show Report'),'url'=>\App\Filament\Pages\EndOfStreamForm::getUrl(['showId'=>$show->id]),'tone'=>'primary'],
        'admin_review' => ['label'=>'Review Streamer Report','url'=>$report?\App\Filament\Resources\StreamerLogResource::getUrl('edit',['record'=>$report]):\App\Filament\Resources\ShowResource::getUrl('view',['record'=>$show]),'tone'=>'warning'],
        'fulfillment' => ['label'=>match($workflow['label']??''){ 'Fulfillment Issues'=>'Resolve Fulfillment','Seal Boxes'=>'Seal Boxes','Build Boxes'=>'Build Boxes','Ready to Complete'=>'Complete Fulfillment',default=>'Pack Show'},'url'=>\App\Filament\Resources\FulfillmentResource::getUrl('view',['record'=>$show]),'tone'=>'primary'],
        'payroll_review','payroll_ready' => ['label'=>$workflowKey==='payroll_ready'?'Open Payroll':'Fix Payroll Inputs','url'=>\App\Filament\Pages\PayrollOverview::getUrl(),'tone'=>$workflowKey==='payroll_ready'?'success':'warning'],
        'payroll' => ['label'=>'Open Pay Run','url'=>$payouts->first()?->batch?\App\Filament\Resources\WeeklyPayoutBatchResource::getUrl('view',['record'=>$payouts->first()->batch]):\App\Filament\Pages\PayrollOverview::getUrl(),'tone'=>'primary'],
        'paid' => ['label'=>'Workflow Complete','url'=>null,'tone'=>'success'],
        default => ['label'=>'Open Show Report','url'=>\App\Filament\Pages\EndOfStreamForm::getUrl(['showId'=>$show->id]),'tone'=>'primary'],
    };
    $blocker = $workflow['blockers'][0] ?? ($workflow['description'] ?? 'No active blocker.');
@endphp
<div class="vx-show-detail space-y-5">
    <section class="vx-card overflow-hidden">
        <div class="p-5 sm:p-6">
            <div class="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between">
                <div class="flex min-w-0 gap-4">
                    <div class="grid h-16 w-16 shrink-0 place-items-center rounded-2xl bg-gradient-to-br from-violet-600 to-indigo-700 text-2xl font-black text-white shadow-sm">V</div>
                    <div class="min-w-0">
                        <div class="flex flex-wrap items-center gap-2 text-xs font-semibold text-gray-500">@if($show->channel)<span>{{ $show->channel->name }}</span>@endif <span class="text-primary-600">Show #{{ $show->id }}</span></div>
                        <h1 class="mt-1 text-2xl font-black tracking-tight text-gray-950 dark:text-white sm:text-3xl">{{ $show->title ?: 'Show #'.$show->id }}</h1>
                        <div class="mt-2 flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-gray-500">
                            <span>{{ $show->show_date?->format('M j, Y') ?? 'Date not set' }}</span>
                            @if($show->start_time)<span>• {{ $show->start_time->format('g:i A') }}</span>@endif
                            @if($show->channel)<span>• {{ $show->channel->name }}</span>@endif
                            <span>• {{ ucfirst(str_replace('_',' ',$show->status ?? 'unknown')) }}</span>
                        </div>
                        <div class="mt-3 flex flex-wrap gap-2">
                            <span class="rounded-full bg-violet-50 px-3 py-1 text-xs font-semibold text-violet-700 dark:bg-violet-500/10 dark:text-violet-300">{{ $workflow['label'] ?? ucfirst(str_replace('_',' ',$workflowKey)) }}</span>
                            <span class="rounded-full bg-gray-100 px-3 py-1 text-xs font-semibold text-gray-600 dark:bg-gray-800 dark:text-gray-300">{{ ucfirst(str_replace('_',' ',$show->status ?? 'unknown')) }}</span>
                            @foreach($show->streamers as $streamer)<span class="rounded-full bg-indigo-50 px-3 py-1 text-xs font-semibold text-indigo-700 dark:bg-indigo-500/10 dark:text-indigo-300">{{ $streamer->name }}</span>@endforeach
                            @if($analyticsMissing)<span class="rounded-full bg-rose-50 px-3 py-1 text-xs font-semibold text-rose-700 dark:bg-rose-500/10 dark:text-rose-300">Whatnot analytics missing</span>@endif
                        </div>
                    </div>
                </div>
                <div class="flex shrink-0 flex-wrap gap-2">
                    <a class="inline-flex min-h-10 items-center justify-center rounded-xl border border-gray-200 bg-white px-4 text-xs font-semibold shadow-sm dark:border-gray-700 dark:bg-gray-900" href="{{ \App\Filament\Resources\ShowResource::getUrl('edit',['record'=>$show]) }}">Edit Show</a>
                    <a class="inline-flex min-h-10 items-center justify-center rounded-xl border border-gray-200 bg-white px-4 text-xs font-semibold shadow-sm dark:border-gray-700 dark:bg-gray-900" href="{{ \App\Filament\Resources\ShipmentResource::getUrl('index',['show'=>$show->id]) }}">Shipments</a>
                    <a class="inline-flex min-h-10 items-center justify-center rounded-xl border border-gray-200 bg-white px-4 text-xs font-semibold shadow-sm dark:border-gray-700 dark:bg-gray-900" href="{{ \App\Filament\Resources\ShowResource::getUrl('inventory',['record'=>$show]) }}">Inventory / COGS</a>
                </div>
            </div>
        </div>
        <div class="grid grid-cols-2 gap-px border-t border-gray-100 bg-gray-100 dark:border-gray-800 dark:bg-gray-800 md:grid-cols-3 xl:grid-cols-6">
            @foreach([
                ['Gross Sales','
        <div class="flex flex-col gap-3 p-5 lg:flex-row lg:items-center lg:overflow-x-auto" aria-label="Show workflow">@foreach($workflowSteps as $key=>$label)@php $idx=array_search($key,$stepKeys,true);$cls=$idx<$currentStep?'done':($idx===$currentStep?'current':'');@endphp<div class="flex min-h-10 items-center gap-2 text-xs font-semibold text-[var(--vx-muted)] {{ $cls }}"><span class="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-[var(--vx-gray-bg)] vx-mono">{{ $idx<$currentStep?'✓':$idx+1 }}</span><span>{{ $label }}</span></div>@if(!$loop->last)<span class="hidden text-[var(--vx-faint)] lg:inline">›</span>@endif @endforeach</div>
        <div class="border-t border-gray-100 p-4 dark:border-gray-800 sm:p-5"><div class="vx-next {{ $primary['tone'] }}"><div><div class="text-[9px] font-bold uppercase tracking-[.12em] opacity-70">Next action</div><div class="mt-1 text-sm font-bold">{{ $primary['label'] }}</div><div class="mt-1 text-[11px] opacity-90">{{ $blocker }}</div></div>@if($primary['url'])<a href="{{ $primary['url'] }}" class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold {{ $primary['tone'] }}">{{ $primary['label'] }}</a>@endif</div></div>
    </section>

    <div class="grid gap-5 xl:grid-cols-[minmax(0,1.55fr)_minmax(320px,.65fr)]">
        <div class="space-y-4">\n            <section class="vx-card p-5"><div><h3>Operations</h3><div class="mt-1 text-xs text-[var(--vx-muted)]">The four operational handoffs that move this show forward.</div></div>
                <div class="flex items-center justify-between gap-4 border-t border-[var(--vx-divider)] py-3"><div><div class="text-sm font-semibold">Streamer Report</div><div class="mt-1 text-xs text-[var(--vx-muted)]">{{ $reportLabel }}{{ $report?->streamer?->name?' · '.$report->streamer->name:'' }}</div></div><a class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold" href="{{ $report?\App\Filament\Resources\StreamerLogResource::getUrl('edit',['record'=>$report]):\App\Filament\Pages\EndOfStreamForm::getUrl(['showId'=>$show->id]) }}">{{ $report?'Review':'Start' }}</a></div>
                <div class="flex items-center justify-between gap-4 border-t border-[var(--vx-divider)] py-3"><div><div class="text-sm font-semibold">Fulfillment</div><div class="mt-1 text-xs text-[var(--vx-muted)]">{{ $show->fulfillmentUsers->pluck('name')->filter()->join(', ') ?: 'Unassigned' }} · {{ $shipments->count() }} shipment(s)</div></div><a class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold" href="{{ \App\Filament\Resources\FulfillmentResource::getUrl('view',['record'=>$show]) }}">Open</a></div>
                <div class="flex items-center justify-between gap-4 border-t border-[var(--vx-divider)] py-3"><div><div class="text-sm font-semibold">Inventory / COGS</div><div class="mt-1 text-xs text-[var(--vx-muted)]">${{ number_format((float)$pnl['cogs'],2) }} approved cost · {{ $show->latestDeductionRequest?'deduction request present':'no deduction request yet' }}</div></div><a class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold" href="{{ \App\Filament\Resources\ShowResource::getUrl('inventory',['record'=>$show]) }}">Breakdown</a></div>
                <div class="flex items-center justify-between gap-4 border-t border-[var(--vx-divider)] py-3"><div><div class="text-sm font-semibold">Payroll</div><div class="mt-1 text-xs text-[var(--vx-muted)]">{{ $payouts->count() }} payout line(s) · ${{ number_format((float)$payouts->sum('calculated_payout'),2) }}</div></div>@if($payouts->first()?->batch)<a class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold" href="{{ \App\Filament\Resources\WeeklyPayoutBatchResource::getUrl('view',['record'=>$payouts->first()->batch]) }}">Open Run</a>@else<a class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold" href="{{ \App\Filament\Pages\PayrollOverview::getUrl() }}">Payroll</a>@endif</div>
            </section>

            <section class="vx-card p-5"><div class="flex items-start justify-between gap-3"><div><h3>Shipment Progress</h3><div class="mt-1 text-xs text-[var(--vx-muted)]">Keep shipment detail secondary unless fulfillment needs it.</div></div><a class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold" href="{{ \App\Filament\Resources\ShipmentResource::getUrl('index',['show'=>$show->id]) }}">View All</a></div><div class="grid grid-cols-3 gap-3 mt-4"><div class="rounded-[10px] border border-[var(--vx-divider)] p-3 text-center"><div class="text-xl font-bold">{{ $shipments->count() }}</div><div class="text-[10px] text-gray-500">Shipments</div></div><div class="rounded-[10px] border border-[var(--vx-divider)] p-3 text-center"><div class="text-xl font-bold">{{ $deliveredShipments }}</div><div class="text-[10px] text-gray-500">Delivered</div></div><div class="rounded-[10px] border border-[var(--vx-divider)] p-3 text-center"><div class="text-xl font-bold">{{ $openShipments }}</div><div class="text-[10px] text-gray-500">Open</div></div></div></section>
        </div>

        <aside class="space-y-4">
            <section class="vx-card overflow-hidden"><div class="border-b border-gray-100 p-5 dark:border-gray-800"><h3>Show Financials</h3><div class="mt-1 text-xs text-[var(--vx-muted)]">A compact operating P&L for the show.</div></div><div class="p-5">@foreach([['Gross Sales',$pnl['gross']],['Whatnot Net',$pnl['net']],['Tips',$pnl['tips']],['COGS',-$pnl['cogs']],['Payroll',-$pnl['payouts']]] as [$label,$value])<div class="flex items-center justify-between gap-3 border-t border-[var(--vx-divider)] py-2 text-sm"><span class="text-gray-500">{{ $label }}</span><strong>${{ number_format((float)$value,2) }}</strong></div>@endforeach<div class="flex items-center justify-between gap-3 border-t border-[var(--vx-divider)] py-2 text-sm"><span class="font-bold">Show Net</span><strong class="{{ $pnl['margin']<0?'vx-bad':'vx-good' }}">${{ number_format((float)$pnl['margin'],2) }} · {{ number_format((float)$pnl['margin_pct'],1) }}%</strong></div></div>@if($analyticsMissing)<div class="mt-4 rounded-xl bg-amber-50 p-3 text-[11px] text-amber-700 dark:bg-amber-950/30 dark:text-amber-300">Whatnot analytics have not been captured for this completed show yet.</div>@endif</section>
            <section class="vx-card p-5"><details><summary class="cursor-pointer list-none"><div class="flex items-center justify-between"><div><h3>Show Details</h3><div class="mt-1 text-xs text-[var(--vx-muted)]">Secondary show and sync metadata.</div></div><span class="text-xs font-bold text-primary-600">View</span></div></summary><div class="mt-3">@foreach([['Orders',$show->units_sold],['Buyers',$show->buyers_count],['Giveaways',$show->giveaways_count],['Peak viewers',$show->max_concurrent_viewers],['Rating',$show->avg_order_rating],['Last sync',$show->last_synced_at?->format('M j, g:i A')]] as [$label,$value])<div class="flex items-center justify-between gap-3 border-t border-[var(--vx-divider)] py-2 text-sm"><span class="text-gray-500">{{ $label }}</span><strong>{{ $value ?? '—' }}</strong></div>@endforeach</div></details></section>
        </aside>
    </div>
</div>
</x-filament-panels::page>.number_format((float)$pnl['gross'],2),'Gross revenue'],
                ['Orders',number_format((int)($show->units_sold ?? 0)),number_format((int)($show->buyers_count ?? 0)).' buyers'],
                ['Shipments',number_format($shipments->count()),number_format($openShipments).' open'],
                ['Whatnot Net','
        <div class="flex flex-col gap-3 p-5 lg:flex-row lg:items-center lg:overflow-x-auto" aria-label="Show workflow">@foreach($workflowSteps as $key=>$label)@php $idx=array_search($key,$stepKeys,true);$cls=$idx<$currentStep?'done':($idx===$currentStep?'current':'');@endphp<div class="flex min-h-10 items-center gap-2 text-xs font-semibold text-[var(--vx-muted)] {{ $cls }}"><span class="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-[var(--vx-gray-bg)] vx-mono">{{ $idx<$currentStep?'✓':$idx+1 }}</span><span>{{ $label }}</span></div>@if(!$loop->last)<span class="hidden text-[var(--vx-faint)] lg:inline">›</span>@endif @endforeach</div>
        <div class="border-t border-gray-100 p-4 dark:border-gray-800 sm:p-5"><div class="vx-next {{ $primary['tone'] }}"><div><div class="text-[9px] font-bold uppercase tracking-[.12em] opacity-70">Next action</div><div class="mt-1 text-sm font-bold">{{ $primary['label'] }}</div><div class="mt-1 text-[11px] opacity-90">{{ $blocker }}</div></div>@if($primary['url'])<a href="{{ $primary['url'] }}" class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold {{ $primary['tone'] }}">{{ $primary['label'] }}</a>@endif</div></div>
    </section>

    <div class="grid gap-6 xl:grid-cols-[minmax(0,1.5fr)_minmax(300px,.6fr)]">
        <div class="space-y-3">
            <section class="vx-card p-5"><div><h3>Workflow Status</h3><div class="mt-1 text-xs text-[var(--vx-muted)]">The four operational handoffs that move this show forward.</div></div>
                <div class="flex items-center justify-between gap-4 border-t border-[var(--vx-divider)] py-3"><div><div class="text-sm font-semibold">Streamer Report</div><div class="mt-1 text-xs text-[var(--vx-muted)]">{{ $reportLabel }}{{ $report?->streamer?->name?' · '.$report->streamer->name:'' }}</div></div><a class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold" href="{{ $report?\App\Filament\Resources\StreamerLogResource::getUrl('edit',['record'=>$report]):\App\Filament\Pages\EndOfStreamForm::getUrl(['showId'=>$show->id]) }}">{{ $report?'Review':'Start' }}</a></div>
                <div class="flex items-center justify-between gap-4 border-t border-[var(--vx-divider)] py-3"><div><div class="text-sm font-semibold">Fulfillment</div><div class="mt-1 text-xs text-[var(--vx-muted)]">{{ $show->fulfillmentUsers->pluck('name')->filter()->join(', ') ?: 'Unassigned' }} · {{ $shipments->count() }} shipment(s)</div></div><a class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold" href="{{ \App\Filament\Resources\FulfillmentResource::getUrl('view',['record'=>$show]) }}">Open</a></div>
                <div class="flex items-center justify-between gap-4 border-t border-[var(--vx-divider)] py-3"><div><div class="text-sm font-semibold">Inventory / COGS</div><div class="mt-1 text-xs text-[var(--vx-muted)]">${{ number_format((float)$pnl['cogs'],2) }} approved cost · {{ $show->latestDeductionRequest?'deduction request present':'no deduction request yet' }}</div></div><a class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold" href="{{ \App\Filament\Resources\ShowResource::getUrl('inventory',['record'=>$show]) }}">Breakdown</a></div>
                <div class="flex items-center justify-between gap-4 border-t border-[var(--vx-divider)] py-3"><div><div class="text-sm font-semibold">Payroll</div><div class="mt-1 text-xs text-[var(--vx-muted)]">{{ $payouts->count() }} payout line(s) · ${{ number_format((float)$payouts->sum('calculated_payout'),2) }}</div></div>@if($payouts->first()?->batch)<a class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold" href="{{ \App\Filament\Resources\WeeklyPayoutBatchResource::getUrl('view',['record'=>$payouts->first()->batch]) }}">Open Run</a>@else<a class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold" href="{{ \App\Filament\Pages\PayrollOverview::getUrl() }}">Payroll</a>@endif</div>
            </section>

            <section class="vx-card p-5"><div class="flex items-start justify-between gap-3"><div><h3>Shipment Progress</h3><div class="mt-1 text-xs text-[var(--vx-muted)]">Keep shipment detail secondary unless fulfillment needs it.</div></div><a class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold" href="{{ \App\Filament\Resources\ShipmentResource::getUrl('index',['show'=>$show->id]) }}">View All</a></div><div class="grid grid-cols-3 gap-3 mt-4"><div class="rounded-[10px] border border-[var(--vx-divider)] p-3 text-center"><div class="text-xl font-bold">{{ $shipments->count() }}</div><div class="text-[10px] text-gray-500">Shipments</div></div><div class="rounded-[10px] border border-[var(--vx-divider)] p-3 text-center"><div class="text-xl font-bold">{{ $deliveredShipments }}</div><div class="text-[10px] text-gray-500">Delivered</div></div><div class="rounded-[10px] border border-[var(--vx-divider)] p-3 text-center"><div class="text-xl font-bold">{{ $openShipments }}</div><div class="text-[10px] text-gray-500">Open</div></div></div></section>
        </div>

        <aside class="space-y-3">
            <section class="vx-card p-5"><h3>Show Financials</h3><div class="mt-1 text-xs text-[var(--vx-muted)]">A compact operating P&L for the show.</div><div class="mt-3">@foreach([['Gross Sales',$pnl['gross']],['Whatnot Net',$pnl['net']],['Tips',$pnl['tips']],['COGS',-$pnl['cogs']],['Payroll',-$pnl['payouts']]] as [$label,$value])<div class="flex items-center justify-between gap-3 border-t border-[var(--vx-divider)] py-2 text-sm"><span class="text-gray-500">{{ $label }}</span><strong>${{ number_format((float)$value,2) }}</strong></div>@endforeach<div class="flex items-center justify-between gap-3 border-t border-[var(--vx-divider)] py-2 text-sm"><span class="font-bold">Show Net</span><strong class="{{ $pnl['margin']<0?'vx-bad':'vx-good' }}">${{ number_format((float)$pnl['margin'],2) }} · {{ number_format((float)$pnl['margin_pct'],1) }}%</strong></div></div>@if($analyticsMissing)<div class="mt-3 rounded-xl bg-amber-50 p-3 text-[11px] text-amber-700 dark:bg-amber-950/30 dark:text-amber-300">Whatnot analytics have not been captured for this completed show yet.</div>@endif</section>
            <section class="vx-card p-5"><details><summary class="cursor-pointer list-none"><div class="flex items-center justify-between"><div><h3>Show Details</h3><div class="mt-1 text-xs text-[var(--vx-muted)]">Secondary show and sync metadata.</div></div><span class="text-xs font-bold text-primary-600">View</span></div></summary><div class="mt-3">@foreach([['Orders',$show->units_sold],['Buyers',$show->buyers_count],['Giveaways',$show->giveaways_count],['Peak viewers',$show->max_concurrent_viewers],['Rating',$show->avg_order_rating],['Last sync',$show->last_synced_at?->format('M j, g:i A')]] as [$label,$value])<div class="flex items-center justify-between gap-3 border-t border-[var(--vx-divider)] py-2 text-sm"><span class="text-gray-500">{{ $label }}</span><strong>{{ $value ?? '—' }}</strong></div>@endforeach</div></details></section>
        </aside>
    </div>
</div>
</x-filament-panels::page>.number_format((float)$pnl['net'],2),'Estimated earnings'],
                ['Payroll','
        <div class="flex flex-col gap-3 p-5 lg:flex-row lg:items-center lg:overflow-x-auto" aria-label="Show workflow">@foreach($workflowSteps as $key=>$label)@php $idx=array_search($key,$stepKeys,true);$cls=$idx<$currentStep?'done':($idx===$currentStep?'current':'');@endphp<div class="flex min-h-10 items-center gap-2 text-xs font-semibold text-[var(--vx-muted)] {{ $cls }}"><span class="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-[var(--vx-gray-bg)] vx-mono">{{ $idx<$currentStep?'✓':$idx+1 }}</span><span>{{ $label }}</span></div>@if(!$loop->last)<span class="hidden text-[var(--vx-faint)] lg:inline">›</span>@endif @endforeach</div>
        <div class="border-t border-gray-100 p-4 dark:border-gray-800 sm:p-5"><div class="vx-next {{ $primary['tone'] }}"><div><div class="text-[9px] font-bold uppercase tracking-[.12em] opacity-70">Next action</div><div class="mt-1 text-sm font-bold">{{ $primary['label'] }}</div><div class="mt-1 text-[11px] opacity-90">{{ $blocker }}</div></div>@if($primary['url'])<a href="{{ $primary['url'] }}" class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold {{ $primary['tone'] }}">{{ $primary['label'] }}</a>@endif</div></div>
    </section>

    <div class="grid gap-6 xl:grid-cols-[minmax(0,1.5fr)_minmax(300px,.6fr)]">
        <div class="space-y-3">
            <section class="vx-card p-5"><div><h3>Workflow Status</h3><div class="mt-1 text-xs text-[var(--vx-muted)]">The four operational handoffs that move this show forward.</div></div>
                <div class="flex items-center justify-between gap-4 border-t border-[var(--vx-divider)] py-3"><div><div class="text-sm font-semibold">Streamer Report</div><div class="mt-1 text-xs text-[var(--vx-muted)]">{{ $reportLabel }}{{ $report?->streamer?->name?' · '.$report->streamer->name:'' }}</div></div><a class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold" href="{{ $report?\App\Filament\Resources\StreamerLogResource::getUrl('edit',['record'=>$report]):\App\Filament\Pages\EndOfStreamForm::getUrl(['showId'=>$show->id]) }}">{{ $report?'Review':'Start' }}</a></div>
                <div class="flex items-center justify-between gap-4 border-t border-[var(--vx-divider)] py-3"><div><div class="text-sm font-semibold">Fulfillment</div><div class="mt-1 text-xs text-[var(--vx-muted)]">{{ $show->fulfillmentUsers->pluck('name')->filter()->join(', ') ?: 'Unassigned' }} · {{ $shipments->count() }} shipment(s)</div></div><a class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold" href="{{ \App\Filament\Resources\FulfillmentResource::getUrl('view',['record'=>$show]) }}">Open</a></div>
                <div class="flex items-center justify-between gap-4 border-t border-[var(--vx-divider)] py-3"><div><div class="text-sm font-semibold">Inventory / COGS</div><div class="mt-1 text-xs text-[var(--vx-muted)]">${{ number_format((float)$pnl['cogs'],2) }} approved cost · {{ $show->latestDeductionRequest?'deduction request present':'no deduction request yet' }}</div></div><a class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold" href="{{ \App\Filament\Resources\ShowResource::getUrl('inventory',['record'=>$show]) }}">Breakdown</a></div>
                <div class="flex items-center justify-between gap-4 border-t border-[var(--vx-divider)] py-3"><div><div class="text-sm font-semibold">Payroll</div><div class="mt-1 text-xs text-[var(--vx-muted)]">{{ $payouts->count() }} payout line(s) · ${{ number_format((float)$payouts->sum('calculated_payout'),2) }}</div></div>@if($payouts->first()?->batch)<a class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold" href="{{ \App\Filament\Resources\WeeklyPayoutBatchResource::getUrl('view',['record'=>$payouts->first()->batch]) }}">Open Run</a>@else<a class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold" href="{{ \App\Filament\Pages\PayrollOverview::getUrl() }}">Payroll</a>@endif</div>
            </section>

            <section class="vx-card p-5"><div class="flex items-start justify-between gap-3"><div><h3>Shipment Progress</h3><div class="mt-1 text-xs text-[var(--vx-muted)]">Keep shipment detail secondary unless fulfillment needs it.</div></div><a class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold" href="{{ \App\Filament\Resources\ShipmentResource::getUrl('index',['show'=>$show->id]) }}">View All</a></div><div class="grid grid-cols-3 gap-3 mt-4"><div class="rounded-[10px] border border-[var(--vx-divider)] p-3 text-center"><div class="text-xl font-bold">{{ $shipments->count() }}</div><div class="text-[10px] text-gray-500">Shipments</div></div><div class="rounded-[10px] border border-[var(--vx-divider)] p-3 text-center"><div class="text-xl font-bold">{{ $deliveredShipments }}</div><div class="text-[10px] text-gray-500">Delivered</div></div><div class="rounded-[10px] border border-[var(--vx-divider)] p-3 text-center"><div class="text-xl font-bold">{{ $openShipments }}</div><div class="text-[10px] text-gray-500">Open</div></div></div></section>
        </div>

        <aside class="space-y-3">
            <section class="vx-card p-5"><h3>Show Financials</h3><div class="mt-1 text-xs text-[var(--vx-muted)]">A compact operating P&L for the show.</div><div class="mt-3">@foreach([['Gross Sales',$pnl['gross']],['Whatnot Net',$pnl['net']],['Tips',$pnl['tips']],['COGS',-$pnl['cogs']],['Payroll',-$pnl['payouts']]] as [$label,$value])<div class="flex items-center justify-between gap-3 border-t border-[var(--vx-divider)] py-2 text-sm"><span class="text-gray-500">{{ $label }}</span><strong>${{ number_format((float)$value,2) }}</strong></div>@endforeach<div class="flex items-center justify-between gap-3 border-t border-[var(--vx-divider)] py-2 text-sm"><span class="font-bold">Show Net</span><strong class="{{ $pnl['margin']<0?'vx-bad':'vx-good' }}">${{ number_format((float)$pnl['margin'],2) }} · {{ number_format((float)$pnl['margin_pct'],1) }}%</strong></div></div>@if($analyticsMissing)<div class="mt-3 rounded-xl bg-amber-50 p-3 text-[11px] text-amber-700 dark:bg-amber-950/30 dark:text-amber-300">Whatnot analytics have not been captured for this completed show yet.</div>@endif</section>
            <section class="vx-card p-5"><details><summary class="cursor-pointer list-none"><div class="flex items-center justify-between"><div><h3>Show Details</h3><div class="mt-1 text-xs text-[var(--vx-muted)]">Secondary show and sync metadata.</div></div><span class="text-xs font-bold text-primary-600">View</span></div></summary><div class="mt-3">@foreach([['Orders',$show->units_sold],['Buyers',$show->buyers_count],['Giveaways',$show->giveaways_count],['Peak viewers',$show->max_concurrent_viewers],['Rating',$show->avg_order_rating],['Last sync',$show->last_synced_at?->format('M j, g:i A')]] as [$label,$value])<div class="flex items-center justify-between gap-3 border-t border-[var(--vx-divider)] py-2 text-sm"><span class="text-gray-500">{{ $label }}</span><strong>{{ $value ?? '—' }}</strong></div>@endforeach</div></details></section>
        </aside>
    </div>
</div>
</x-filament-panels::page>.number_format((float)$pnl['payouts'],2),$payouts->count().' payout lines'],
                ['Show Net','
        <div class="flex flex-col gap-3 p-5 lg:flex-row lg:items-center lg:overflow-x-auto" aria-label="Show workflow">@foreach($workflowSteps as $key=>$label)@php $idx=array_search($key,$stepKeys,true);$cls=$idx<$currentStep?'done':($idx===$currentStep?'current':'');@endphp<div class="flex min-h-10 items-center gap-2 text-xs font-semibold text-[var(--vx-muted)] {{ $cls }}"><span class="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-[var(--vx-gray-bg)] vx-mono">{{ $idx<$currentStep?'✓':$idx+1 }}</span><span>{{ $label }}</span></div>@if(!$loop->last)<span class="hidden text-[var(--vx-faint)] lg:inline">›</span>@endif @endforeach</div>
        <div class="border-t border-gray-100 p-4 dark:border-gray-800 sm:p-5"><div class="vx-next {{ $primary['tone'] }}"><div><div class="text-[9px] font-bold uppercase tracking-[.12em] opacity-70">Next action</div><div class="mt-1 text-sm font-bold">{{ $primary['label'] }}</div><div class="mt-1 text-[11px] opacity-90">{{ $blocker }}</div></div>@if($primary['url'])<a href="{{ $primary['url'] }}" class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold {{ $primary['tone'] }}">{{ $primary['label'] }}</a>@endif</div></div>
    </section>

    <div class="grid gap-6 xl:grid-cols-[minmax(0,1.5fr)_minmax(300px,.6fr)]">
        <div class="space-y-3">
            <section class="vx-card p-5"><div><h3>Workflow Status</h3><div class="mt-1 text-xs text-[var(--vx-muted)]">The four operational handoffs that move this show forward.</div></div>
                <div class="flex items-center justify-between gap-4 border-t border-[var(--vx-divider)] py-3"><div><div class="text-sm font-semibold">Streamer Report</div><div class="mt-1 text-xs text-[var(--vx-muted)]">{{ $reportLabel }}{{ $report?->streamer?->name?' · '.$report->streamer->name:'' }}</div></div><a class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold" href="{{ $report?\App\Filament\Resources\StreamerLogResource::getUrl('edit',['record'=>$report]):\App\Filament\Pages\EndOfStreamForm::getUrl(['showId'=>$show->id]) }}">{{ $report?'Review':'Start' }}</a></div>
                <div class="flex items-center justify-between gap-4 border-t border-[var(--vx-divider)] py-3"><div><div class="text-sm font-semibold">Fulfillment</div><div class="mt-1 text-xs text-[var(--vx-muted)]">{{ $show->fulfillmentUsers->pluck('name')->filter()->join(', ') ?: 'Unassigned' }} · {{ $shipments->count() }} shipment(s)</div></div><a class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold" href="{{ \App\Filament\Resources\FulfillmentResource::getUrl('view',['record'=>$show]) }}">Open</a></div>
                <div class="flex items-center justify-between gap-4 border-t border-[var(--vx-divider)] py-3"><div><div class="text-sm font-semibold">Inventory / COGS</div><div class="mt-1 text-xs text-[var(--vx-muted)]">${{ number_format((float)$pnl['cogs'],2) }} approved cost · {{ $show->latestDeductionRequest?'deduction request present':'no deduction request yet' }}</div></div><a class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold" href="{{ \App\Filament\Resources\ShowResource::getUrl('inventory',['record'=>$show]) }}">Breakdown</a></div>
                <div class="flex items-center justify-between gap-4 border-t border-[var(--vx-divider)] py-3"><div><div class="text-sm font-semibold">Payroll</div><div class="mt-1 text-xs text-[var(--vx-muted)]">{{ $payouts->count() }} payout line(s) · ${{ number_format((float)$payouts->sum('calculated_payout'),2) }}</div></div>@if($payouts->first()?->batch)<a class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold" href="{{ \App\Filament\Resources\WeeklyPayoutBatchResource::getUrl('view',['record'=>$payouts->first()->batch]) }}">Open Run</a>@else<a class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold" href="{{ \App\Filament\Pages\PayrollOverview::getUrl() }}">Payroll</a>@endif</div>
            </section>

            <section class="vx-card p-5"><div class="flex items-start justify-between gap-3"><div><h3>Shipment Progress</h3><div class="mt-1 text-xs text-[var(--vx-muted)]">Keep shipment detail secondary unless fulfillment needs it.</div></div><a class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold" href="{{ \App\Filament\Resources\ShipmentResource::getUrl('index',['show'=>$show->id]) }}">View All</a></div><div class="grid grid-cols-3 gap-3 mt-4"><div class="rounded-[10px] border border-[var(--vx-divider)] p-3 text-center"><div class="text-xl font-bold">{{ $shipments->count() }}</div><div class="text-[10px] text-gray-500">Shipments</div></div><div class="rounded-[10px] border border-[var(--vx-divider)] p-3 text-center"><div class="text-xl font-bold">{{ $deliveredShipments }}</div><div class="text-[10px] text-gray-500">Delivered</div></div><div class="rounded-[10px] border border-[var(--vx-divider)] p-3 text-center"><div class="text-xl font-bold">{{ $openShipments }}</div><div class="text-[10px] text-gray-500">Open</div></div></div></section>
        </div>

        <aside class="space-y-3">
            <section class="vx-card p-5"><h3>Show Financials</h3><div class="mt-1 text-xs text-[var(--vx-muted)]">A compact operating P&L for the show.</div><div class="mt-3">@foreach([['Gross Sales',$pnl['gross']],['Whatnot Net',$pnl['net']],['Tips',$pnl['tips']],['COGS',-$pnl['cogs']],['Payroll',-$pnl['payouts']]] as [$label,$value])<div class="flex items-center justify-between gap-3 border-t border-[var(--vx-divider)] py-2 text-sm"><span class="text-gray-500">{{ $label }}</span><strong>${{ number_format((float)$value,2) }}</strong></div>@endforeach<div class="flex items-center justify-between gap-3 border-t border-[var(--vx-divider)] py-2 text-sm"><span class="font-bold">Show Net</span><strong class="{{ $pnl['margin']<0?'vx-bad':'vx-good' }}">${{ number_format((float)$pnl['margin'],2) }} · {{ number_format((float)$pnl['margin_pct'],1) }}%</strong></div></div>@if($analyticsMissing)<div class="mt-3 rounded-xl bg-amber-50 p-3 text-[11px] text-amber-700 dark:bg-amber-950/30 dark:text-amber-300">Whatnot analytics have not been captured for this completed show yet.</div>@endif</section>
            <section class="vx-card p-5"><details><summary class="cursor-pointer list-none"><div class="flex items-center justify-between"><div><h3>Show Details</h3><div class="mt-1 text-xs text-[var(--vx-muted)]">Secondary show and sync metadata.</div></div><span class="text-xs font-bold text-primary-600">View</span></div></summary><div class="mt-3">@foreach([['Orders',$show->units_sold],['Buyers',$show->buyers_count],['Giveaways',$show->giveaways_count],['Peak viewers',$show->max_concurrent_viewers],['Rating',$show->avg_order_rating],['Last sync',$show->last_synced_at?->format('M j, g:i A')]] as [$label,$value])<div class="flex items-center justify-between gap-3 border-t border-[var(--vx-divider)] py-2 text-sm"><span class="text-gray-500">{{ $label }}</span><strong>{{ $value ?? '—' }}</strong></div>@endforeach</div></details></section>
        </aside>
    </div>
</div>
</x-filament-panels::page>.number_format((float)$pnl['margin'],2),number_format((float)$pnl['margin_pct'],1).'% margin'],
            ] as [$label,$value,$sub])
                <div class="bg-white p-4 dark:bg-gray-900"><div class="text-[11px] font-semibold uppercase tracking-wide text-gray-400">{{ $label }}</div><div class="mt-1 text-xl font-black tabular-nums text-gray-950 dark:text-white">{{ $value }}</div><div class="mt-1 text-[11px] text-gray-400">{{ $sub }}</div></div>
            @endforeach
        </div>
    </section>

    <section class="vx-card">
        <div class="flex flex-col gap-3 p-5 lg:flex-row lg:items-center lg:overflow-x-auto" aria-label="Show workflow">@foreach($workflowSteps as $key=>$label)@php $idx=array_search($key,$stepKeys,true);$cls=$idx<$currentStep?'done':($idx===$currentStep?'current':'');@endphp<div class="flex min-h-10 items-center gap-2 text-xs font-semibold text-[var(--vx-muted)] {{ $cls }}"><span class="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-[var(--vx-gray-bg)] vx-mono">{{ $idx<$currentStep?'✓':$idx+1 }}</span><span>{{ $label }}</span></div>@if(!$loop->last)<span class="hidden text-[var(--vx-faint)] lg:inline">›</span>@endif @endforeach</div>
        <div class="border-t border-gray-100 p-4 dark:border-gray-800 sm:p-5"><div class="vx-next {{ $primary['tone'] }}"><div><div class="text-[9px] font-bold uppercase tracking-[.12em] opacity-70">Next action</div><div class="mt-1 text-sm font-bold">{{ $primary['label'] }}</div><div class="mt-1 text-[11px] opacity-90">{{ $blocker }}</div></div>@if($primary['url'])<a href="{{ $primary['url'] }}" class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold {{ $primary['tone'] }}">{{ $primary['label'] }}</a>@endif</div></div>
    </section>

    <div class="grid gap-6 xl:grid-cols-[minmax(0,1.5fr)_minmax(300px,.6fr)]">
        <div class="space-y-3">
            <section class="vx-card p-5"><div><h3>Workflow Status</h3><div class="mt-1 text-xs text-[var(--vx-muted)]">The four operational handoffs that move this show forward.</div></div>
                <div class="flex items-center justify-between gap-4 border-t border-[var(--vx-divider)] py-3"><div><div class="text-sm font-semibold">Streamer Report</div><div class="mt-1 text-xs text-[var(--vx-muted)]">{{ $reportLabel }}{{ $report?->streamer?->name?' · '.$report->streamer->name:'' }}</div></div><a class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold" href="{{ $report?\App\Filament\Resources\StreamerLogResource::getUrl('edit',['record'=>$report]):\App\Filament\Pages\EndOfStreamForm::getUrl(['showId'=>$show->id]) }}">{{ $report?'Review':'Start' }}</a></div>
                <div class="flex items-center justify-between gap-4 border-t border-[var(--vx-divider)] py-3"><div><div class="text-sm font-semibold">Fulfillment</div><div class="mt-1 text-xs text-[var(--vx-muted)]">{{ $show->fulfillmentUsers->pluck('name')->filter()->join(', ') ?: 'Unassigned' }} · {{ $shipments->count() }} shipment(s)</div></div><a class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold" href="{{ \App\Filament\Resources\FulfillmentResource::getUrl('view',['record'=>$show]) }}">Open</a></div>
                <div class="flex items-center justify-between gap-4 border-t border-[var(--vx-divider)] py-3"><div><div class="text-sm font-semibold">Inventory / COGS</div><div class="mt-1 text-xs text-[var(--vx-muted)]">${{ number_format((float)$pnl['cogs'],2) }} approved cost · {{ $show->latestDeductionRequest?'deduction request present':'no deduction request yet' }}</div></div><a class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold" href="{{ \App\Filament\Resources\ShowResource::getUrl('inventory',['record'=>$show]) }}">Breakdown</a></div>
                <div class="flex items-center justify-between gap-4 border-t border-[var(--vx-divider)] py-3"><div><div class="text-sm font-semibold">Payroll</div><div class="mt-1 text-xs text-[var(--vx-muted)]">{{ $payouts->count() }} payout line(s) · ${{ number_format((float)$payouts->sum('calculated_payout'),2) }}</div></div>@if($payouts->first()?->batch)<a class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold" href="{{ \App\Filament\Resources\WeeklyPayoutBatchResource::getUrl('view',['record'=>$payouts->first()->batch]) }}">Open Run</a>@else<a class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold" href="{{ \App\Filament\Pages\PayrollOverview::getUrl() }}">Payroll</a>@endif</div>
            </section>

            <section class="vx-card p-5"><div class="flex items-start justify-between gap-3"><div><h3>Shipment Progress</h3><div class="mt-1 text-xs text-[var(--vx-muted)]">Keep shipment detail secondary unless fulfillment needs it.</div></div><a class="inline-flex min-h-10 items-center justify-center rounded-[10px] border border-[var(--vx-border)] px-3 text-xs font-semibold" href="{{ \App\Filament\Resources\ShipmentResource::getUrl('index',['show'=>$show->id]) }}">View All</a></div><div class="grid grid-cols-3 gap-3 mt-4"><div class="rounded-[10px] border border-[var(--vx-divider)] p-3 text-center"><div class="text-xl font-bold">{{ $shipments->count() }}</div><div class="text-[10px] text-gray-500">Shipments</div></div><div class="rounded-[10px] border border-[var(--vx-divider)] p-3 text-center"><div class="text-xl font-bold">{{ $deliveredShipments }}</div><div class="text-[10px] text-gray-500">Delivered</div></div><div class="rounded-[10px] border border-[var(--vx-divider)] p-3 text-center"><div class="text-xl font-bold">{{ $openShipments }}</div><div class="text-[10px] text-gray-500">Open</div></div></div></section>
        </div>

        <aside class="space-y-3">
            <section class="vx-card p-5"><h3>Show Financials</h3><div class="mt-1 text-xs text-[var(--vx-muted)]">A compact operating P&L for the show.</div><div class="mt-3">@foreach([['Gross Sales',$pnl['gross']],['Whatnot Net',$pnl['net']],['Tips',$pnl['tips']],['COGS',-$pnl['cogs']],['Payroll',-$pnl['payouts']]] as [$label,$value])<div class="flex items-center justify-between gap-3 border-t border-[var(--vx-divider)] py-2 text-sm"><span class="text-gray-500">{{ $label }}</span><strong>${{ number_format((float)$value,2) }}</strong></div>@endforeach<div class="flex items-center justify-between gap-3 border-t border-[var(--vx-divider)] py-2 text-sm"><span class="font-bold">Show Net</span><strong class="{{ $pnl['margin']<0?'vx-bad':'vx-good' }}">${{ number_format((float)$pnl['margin'],2) }} · {{ number_format((float)$pnl['margin_pct'],1) }}%</strong></div></div>@if($analyticsMissing)<div class="mt-3 rounded-xl bg-amber-50 p-3 text-[11px] text-amber-700 dark:bg-amber-950/30 dark:text-amber-300">Whatnot analytics have not been captured for this completed show yet.</div>@endif</section>
            <section class="vx-card p-5"><details><summary class="cursor-pointer list-none"><div class="flex items-center justify-between"><div><h3>Show Details</h3><div class="mt-1 text-xs text-[var(--vx-muted)]">Secondary show and sync metadata.</div></div><span class="text-xs font-bold text-primary-600">View</span></div></summary><div class="mt-3">@foreach([['Orders',$show->units_sold],['Buyers',$show->buyers_count],['Giveaways',$show->giveaways_count],['Peak viewers',$show->max_concurrent_viewers],['Rating',$show->avg_order_rating],['Last sync',$show->last_synced_at?->format('M j, g:i A')]] as [$label,$value])<div class="flex items-center justify-between gap-3 border-t border-[var(--vx-divider)] py-2 text-sm"><span class="text-gray-500">{{ $label }}</span><strong>{{ $value ?? '—' }}</strong></div>@endforeach</div></details></section>
        </aside>
    </div>
</div>
</x-filament-panels::page>