<x-filament-panels::page>
@php $pct=(float)($streamer['payout_percentage']??0); $ship=(float)$streamer_burden_per_shipment; $hour=(float)$streamer_burden_per_hour; @endphp
<div class="space-y-6">
    <div><p class="text-sm text-gray-500 dark:text-gray-400">Every streamer uses the same Streamer Log spreadsheet calculation by default. Only add an individual override when that person's terms are actually different.</p></div>

    <div class="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm dark:border-gray-800 dark:bg-gray-900">
        <div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-[.16em] text-primary-500">Default streamer calculation</p><h2 class="mt-1 text-xl font-bold">Streamer Pay Formula</h2><p class="mt-1 max-w-2xl text-sm text-gray-500">This is the standard calculation from the Streamer Log sheet and applies to every streamer unless you explicitly override that person below.</p></div><span class="rounded-full bg-primary-50 px-3 py-1 text-xs font-bold text-primary-700 dark:bg-primary-950/40 dark:text-primary-300">Weekly · all streamers</span></div>
        <div class="mt-6 grid gap-4 md:grid-cols-3">
            <label class="rounded-xl border border-gray-200 p-4 dark:border-gray-700"><span class="text-xs font-semibold text-gray-500">Streamer Pay %</span><div class="mt-2 flex items-center gap-2"><input wire:model.live.debounce.300ms="streamer.payout_percentage" type="number" step=".01" class="w-full rounded-lg border-gray-300 bg-gray-50 text-lg font-bold dark:border-gray-600 dark:bg-gray-800"><span class="font-bold">%</span></div></label>
            <label class="rounded-xl border border-gray-200 p-4 dark:border-gray-700"><span class="text-xs font-semibold text-gray-500">Burden Per Shipment</span><div class="mt-2 flex items-center gap-2"><span class="font-bold">$</span><input wire:model.live.debounce.300ms="streamer_burden_per_shipment" type="number" step=".01" class="w-full rounded-lg border-gray-300 bg-gray-50 text-lg font-bold dark:border-gray-600 dark:bg-gray-800"></div></label>
            <label class="rounded-xl border border-gray-200 p-4 dark:border-gray-700"><span class="text-xs font-semibold text-gray-500">Burden Per Hour</span><div class="mt-2 flex items-center gap-2"><span class="font-bold">$</span><input wire:model.live.debounce.300ms="streamer_burden_per_hour" type="number" step=".01" class="w-full rounded-lg border-gray-300 bg-gray-50 text-lg font-bold dark:border-gray-600 dark:bg-gray-800"></div></label>
        </div>
        <div class="mt-5 rounded-xl border border-primary-200 bg-primary-50/60 p-5 dark:border-primary-900 dark:bg-primary-950/20"><div class="text-xs font-bold uppercase tracking-wider text-primary-600">Standard calculation</div><div class="mt-3 space-y-2 font-mono text-sm"><div>Product Cost = Σ (Inventory Cost × Quantity Sold)</div><div>Burden = (Shipments × ${{number_format($ship,2)}}) + (Hours Worked × ${{number_format($hour,2)}})</div><div>Net Revenue = Gross Revenue − Product Cost − Burden</div><div class="font-bold text-primary-700 dark:text-primary-300">Streamer Pay = Net Revenue × {{number_format($pct,2)}}%</div></div></div>
        <details class="mt-5 rounded-xl border border-gray-200 p-4 dark:border-gray-700"><summary class="cursor-pointer text-sm font-bold">Advanced: change the team calculation</summary><p class="mt-2 text-xs text-gray-500">Normally leave this blank. Use it only if the standard spreadsheet calculation itself changes for all streamers.</p><textarea wire:model="streamer.custom_payout_formula" rows="3" class="mt-3 w-full rounded-lg border-gray-300 bg-gray-50 font-mono text-sm dark:border-gray-600 dark:bg-gray-800" placeholder="Optional team-wide custom formula"></textarea></details>
    </div>

    <div class="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm dark:border-gray-800 dark:bg-gray-900">
        <h2 class="text-lg font-bold">Streamer-Specific Adjustments</h2><p class="mt-1 text-sm text-gray-500">Everyone below inherits the standard calculation. Select a streamer only when you need to change their percentage or give that person a custom calculation.</p>
        <div class="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">@foreach($this->members->where('member_type','streamer') as $member) @php $pay=$member->effectiveCompensation(); @endphp <button wire:click="editMember({{$member->id}})" class="rounded-xl border border-gray-200 p-4 text-left transition hover:border-primary-500 dark:border-gray-700"><div class="font-bold">{{$member->name}}</div><div class="mt-1 text-xs text-gray-500">{{number_format((float)($pay['effective']['payout_percentage']??0),2)}}% @if(count($pay['overrides']??[])) · Individual Adjustment @else · Standard Team Calculation @endif</div></button>@endforeach</div>
        @if($editing_member_id) @php $editingMember=\App\Models\Streamer::find($editing_member_id); @endphp
        <div class="mt-5 rounded-xl border-2 border-primary-300 p-5 dark:border-primary-800"><div class="flex items-center justify-between"><div><div class="text-xs font-bold uppercase text-primary-600">Adjust streamer</div><div class="text-lg font-bold">{{$editingMember?->name}}</div></div><button wire:click="closeMemberEditor" class="text-sm text-gray-500">Close</button></div>
            <div class="mt-4 grid gap-4 md:grid-cols-2"><label class="rounded-lg border p-3"><span class="flex gap-2 text-sm font-bold"><input type="checkbox" wire:model="member_override_enabled.payout_percentage">Use a different Streamer Pay %</span><input wire:model="member_override_values.payout_percentage" type="number" step=".01" class="mt-2 w-full rounded-lg border-gray-300 bg-gray-50 dark:bg-gray-800"></label><label class="rounded-lg border p-3"><span class="flex gap-2 text-sm font-bold"><input type="checkbox" wire:model="member_override_enabled.custom_payout_formula">Use a different calculation</span><textarea wire:model="member_override_values.custom_payout_formula" rows="3" class="mt-2 w-full rounded-lg border-gray-300 bg-gray-50 font-mono text-sm dark:bg-gray-800" placeholder="Only for this streamer"></textarea></label></div>
            <div class="mt-4 flex justify-end gap-3"><button wire:click="resetMemberOverrides({{$editingMember->id}})" class="rounded-lg border px-4 py-2 text-sm font-bold">Reset to Standard Calculation</button><button wire:click="saveMemberOverrides" class="rounded-lg bg-primary-600 px-4 py-2 text-sm font-bold text-white">Save Adjustment</button></div>
        </div>@endif
    </div>

    <div class="rounded-2xl border border-dashed border-gray-300 bg-gray-50 p-6 dark:border-gray-700 dark:bg-gray-900/60"><div class="flex flex-wrap items-center justify-between gap-4"><div><div class="flex items-center gap-2"><h2 class="text-lg font-bold">Fulfillment Payment Structure</h2><span class="rounded-full bg-amber-100 px-2.5 py-1 text-xs font-bold text-amber-800 dark:bg-amber-950/40 dark:text-amber-300">Coming Soon</span></div><p class="mt-2 max-w-2xl text-sm text-gray-500">Fulfillment pay stays separate from the streamer calculation and can be finalized when that workflow is ready.</p></div><div class="rounded-xl border border-gray-200 bg-white px-4 py-3 text-sm text-gray-500 dark:border-gray-700 dark:bg-gray-900">No fulfillment settings are required yet.</div></div></div>

    <details class="rounded-2xl border border-gray-200 bg-white p-6 dark:border-gray-800 dark:bg-gray-900"><summary class="cursor-pointer text-lg font-bold">Pay Run Automation</summary><div class="mt-4 grid gap-3 md:grid-cols-3"><label class="rounded-lg border p-4 text-sm font-bold"><input class="mr-2" type="checkbox" wire:model="payroll_auto_setup_enabled">Automatic weekly setup</label><label class="rounded-lg border p-4 text-sm font-bold"><input class="mr-2" type="checkbox" wire:model="payroll_auto_recalculate_drafts">Recalculate drafts</label><label class="rounded-lg border p-4 text-sm font-bold"><input class="mr-2" type="checkbox" wire:model="payroll_include_zero_activity">Include no-activity members</label></div></details>
    <div class="flex justify-end"><button wire:click="save" class="rounded-xl bg-primary-600 px-6 py-3 text-sm font-bold text-white shadow-lg">Save Streamer Pay Calculation</button></div>
</div>
</x-filament-panels::page>
