<x-filament-panels::page>
<div class="space-y-5">
@if(auth()->user()->isStreamer() && !auth()->user()->isAdmin() && auth()->user()->streamer) @livewire('create-manual-show',['streamer'=>auth()->user()->streamer]) @endif

<section class="rounded-xl border border-gray-200 bg-white p-4 dark:border-gray-700 dark:bg-gray-900">
 <div class="mb-3 flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-sm font-semibold">Show period</h2><p class="text-xs text-gray-500">Choose a week, month, rolling period, or exact dates. Your selection stays in the URL.</p></div><div class="flex rounded-lg border dark:border-gray-700"><button wire:click="$set('viewMode','list')" class="px-3 py-2 text-sm {{ $viewMode==='list'?'bg-primary-600 text-white':'' }}">List</button><button wire:click="$set('viewMode','calendar')" class="px-3 py-2 text-sm {{ $viewMode==='calendar'?'bg-primary-600 text-white':'' }}">Calendar</button></div></div>
 <div class="flex flex-wrap items-end gap-3">
  <button wire:click="previousPeriod" class="rounded-lg border px-3 py-2 dark:border-gray-700">‹</button>
  <div><label class="mb-1 block text-xs text-gray-500">Period</label><select wire:model.live="datePreset" class="rounded-lg border-gray-300 bg-white text-sm dark:border-gray-600 dark:bg-gray-800"><option value="this_week">This week</option><option value="last_week">Last week</option><option value="this_month">This month</option><option value="last_month">Last month</option><option value="last_30">Last 30 days</option><option value="custom">Custom</option></select></div>
  <div><label class="mb-1 block text-xs text-gray-500">From</label><input type="date" wire:model.live="dateFrom" wire:change="$set('datePreset','custom')" class="rounded-lg border-gray-300 bg-white text-sm dark:border-gray-600 dark:bg-gray-800"></div>
  <div><label class="mb-1 block text-xs text-gray-500">To</label><input type="date" wire:model.live="dateTo" wire:change="$set('datePreset','custom')" class="rounded-lg border-gray-300 bg-white text-sm dark:border-gray-600 dark:bg-gray-800"></div>
  <button wire:click="nextPeriod" class="rounded-lg border px-3 py-2 dark:border-gray-700">›</button><div class="ml-auto rounded-lg bg-gray-50 px-3 py-2 text-sm font-semibold dark:bg-gray-800">{{ $this->dateRangeLabel() }}</div>
 </div>
</section>

<section class="rounded-xl border border-gray-200 bg-white p-4 dark:border-gray-700 dark:bg-gray-900">
 <div class="mb-3 flex items-center justify-between"><div><h2 class="text-sm font-semibold">Filter shows</h2><p class="text-xs text-gray-500">These filters apply to both list and calendar.</p></div><button wire:click="clearFilters" class="text-sm font-medium text-primary-600">Reset</button></div>
 <div class="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-5"><input type="search" wire:model.live.debounce.300ms="searchQuery" placeholder="Search title or Whatnot ID…" class="rounded-lg border-gray-300 bg-white text-sm dark:border-gray-600 dark:bg-gray-800"><select wire:model.live="filterTimeframe" class="rounded-lg border-gray-300 bg-white text-sm dark:border-gray-600 dark:bg-gray-800"><option value="all">All in period</option><option value="upcoming">Upcoming</option><option value="past">Past / due</option><option value="attention">Needs submission</option></select><select wire:model.live="filterStatus" class="rounded-lg border-gray-300 bg-white text-sm dark:border-gray-600 dark:bg-gray-800"><option value="all">All statuses</option>@foreach(\App\Models\Show::statusLabels() as $v=>$l)<option value="{{ $v }}">{{ $l }}</option>@endforeach</select>@if(auth()->user()->isAdmin())<select wire:model.live="filterStreamer" class="rounded-lg border-gray-300 bg-white text-sm dark:border-gray-600 dark:bg-gray-800"><option value="">All streamers</option>@foreach($this->streamers as $st)<option value="{{ $st->id }}">{{ $st->name }}</option>@endforeach</select>@endif<select wire:model.live="sortBy" class="rounded-lg border-gray-300 bg-white text-sm dark:border-gray-600 dark:bg-gray-800"><option value="date">Date — newest</option><option value="oldest">Date — oldest</option><option value="revenue">Revenue — highest</option></select></div>
</section>

@php $stats=$this->shows;$upcoming=$stats->filter(fn($s)=>!$this->isShowDue($s))->count();$due=$stats->filter(fn($s)=>$this->isShowDue($s))->count();$orders=$stats->sum('orders_count');$shipments=$stats->sum('shipments_count');$gross=$stats->sum('gross_revenue');$net=$stats->sum('whatnot_net'); @endphp
<div class="grid grid-cols-2 gap-3 lg:grid-cols-6">@foreach([['Shows',$stats->count()],['Upcoming',$upcoming],['Orders',number_format($orders)],['Shipments',number_format($shipments)],['Gross','$'.number_format($gross,0)],['Est. Net','$'.number_format($net,0)]] as [$l,$v])<div class="rounded-xl border bg-white p-4 dark:border-gray-700 dark:bg-gray-900"><div class="text-xs text-gray-500">{{ $l }}</div><div class="mt-1 text-xl font-semibold">{{ $v }}</div></div>@endforeach</div>

@if($viewMode==='calendar')
<section class="overflow-x-auto rounded-xl border bg-white p-4 dark:border-gray-700 dark:bg-gray-900"><div class="min-w-[900px]"><div class="grid grid-cols-7 border-b text-center text-xs font-semibold uppercase text-gray-500">@foreach(['Mon','Tue','Wed','Thu','Fri','Sat','Sun'] as $d)<div class="p-2">{{ $d }}</div>@endforeach</div>@foreach($this->calendarWeeks as $week)<div class="grid grid-cols-7">@foreach($week as $day)<div class="min-h-36 border-b border-r p-2 dark:border-gray-800 {{ !$day['in_range']?'opacity-35 bg-gray-50 dark:bg-gray-950':'' }}"><div class="mb-2 text-xs font-semibold {{ $day['date']->isToday()?'text-primary-600':'' }}">{{ $day['date']->format('M j') }}</div><div class="space-y-1">@foreach($day['shows'] as $show)<a href="{{ $this->showUrl($show->id) }}" class="block rounded-lg border bg-white p-2 text-xs hover:border-primary-400 dark:border-gray-700 dark:bg-gray-800"><div class="truncate font-semibold">{{ $show->title }}</div><div class="mt-1 truncate text-gray-500">{{ $show->start_time?->format('g:i A') ?: 'Time TBD' }} · {{ $show->streamers->pluck('name')->join(', ') ?: 'Unassigned' }}</div>@if($show->gross_revenue>0)<div class="mt-1 font-semibold">${{ number_format((float)$show->gross_revenue,0) }} gross</div>@endif</a>@endforeach</div></div>@endforeach</div>@endforeach</div></section>
@else
<section class="overflow-hidden rounded-xl border bg-white dark:border-gray-700 dark:bg-gray-900"><div class="hidden overflow-x-auto md:block"><table class="w-full text-sm"><thead class="border-b bg-gray-50 text-xs uppercase text-gray-500 dark:bg-gray-800"><tr><th class="px-4 py-3 text-left">Show</th><th class="px-4 py-3 text-left">Streamer</th><th class="px-4 py-3 text-left">Schedule</th><th class="px-4 py-3 text-right">Gross</th><th class="px-4 py-3 text-right">Est. Net</th><th class="px-4 py-3 text-center">Orders</th><th class="px-4 py-3 text-center">Shipments</th><th class="px-4 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y dark:divide-gray-800">@forelse($this->shows as $show)<tr><td class="px-4 py-4"><a href="{{ $this->showUrl($show->id) }}" class="font-semibold hover:text-primary-600">{{ $show->title }}</a><div class="text-xs text-gray-400">{{ $show->whatnot_show_id ?? 'Manual #'.$show->id }}</div></td><td class="px-4 py-4">{{ $show->streamers->pluck('name')->join(', ') ?: 'Unassigned' }}</td><td class="px-4 py-4">{{ $show->show_date?->format('M j, Y') }}<div class="text-xs text-gray-400">{{ $show->start_time?->format('g:i A') ?: 'Time not set' }}</div></td><td class="px-4 py-4 text-right font-semibold">${{ number_format((float)$show->gross_revenue,2) }}</td><td class="px-4 py-4 text-right">${{ number_format((float)$show->whatnot_net,2) }}</td><td class="px-4 py-4 text-center">{{ $show->orders_count }}</td><td class="px-4 py-4 text-center"><a href="{{ $this->shipmentsUrl($show->id) }}" class="text-primary-600">{{ $show->shipments_count }}</a></td><td class="px-4 py-4 text-right"><a href="{{ $this->showUrl($show->id) }}" class="rounded-lg border px-2.5 py-1.5 text-xs">View</a> @if(\App\Filament\Resources\ShowResource::canEdit($show))<a href="{{ $this->editUrl($show->id) }}" class="rounded-lg border px-2.5 py-1.5 text-xs">Edit</a>@endif</td></tr>@empty<tr><td colspan="8" class="p-12 text-center text-gray-500">No shows match this period and filters.</td></tr>@endforelse</tbody></table></div><div class="divide-y md:hidden dark:divide-gray-800">@forelse($this->shows as $show)<article class="p-4"><a href="{{ $this->showUrl($show->id) }}" class="font-semibold">{{ $show->title }}</a><div class="mt-1 text-xs text-gray-500">{{ $show->show_date?->format('M j, Y') }} · {{ $show->streamers->pluck('name')->join(', ') ?: 'Unassigned' }}</div><div class="mt-3 grid grid-cols-2 gap-2 text-sm"><div><span class="text-xs text-gray-400">Gross</span><div>${{ number_format((float)$show->gross_revenue,2) }}</div></div><div><span class="text-xs text-gray-400">Est. Net</span><div>${{ number_format((float)$show->whatnot_net,2) }}</div></div><div><span class="text-xs text-gray-400">Orders</span><div>{{ $show->orders_count }}</div></div><div><span class="text-xs text-gray-400">Shipments</span><div>{{ $show->shipments_count }}</div></div></div></article>@empty<div class="p-10 text-center text-gray-500">No shows match.</div>@endforelse</div></section>
@endif
</div>
</x-filament-panels::page>
