<x-filament-panels::page>
@php $s=$this->streamSnapshot; @endphp
<style>
.vx-streams{max-width:1440px;margin:0 auto}.vx-card{border:1px solid rgb(229 231 235);background:white;border-radius:18px;box-shadow:0 1px 2px rgba(15,23,42,.03)}.dark .vx-card{border-color:#263248;background:#101827}.vx-stream-kpis{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:12px}.vx-stream-kpi{padding:18px}.vx-stream-grid{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(320px,.8fr);gap:16px}.vx-row{display:flex;align-items:center;gap:12px;padding:14px 0;border-top:1px solid rgb(243 244 246)}.dark .vx-row{border-color:#1f2937}.vx-mini-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.vx-action{display:flex;align-items:center;gap:12px;border:1px solid rgb(229 231 235);border-radius:14px;padding:13px;transition:.15s}.dark .vx-action{border-color:#263248}.vx-action:hover{border-color:#8b5cf6;background:rgba(124,58,237,.04)}
@media(max-width:1100px){.vx-stream-kpis{grid-template-columns:repeat(3,1fr)}.vx-stream-grid{grid-template-columns:1fr}}
@media(max-width:700px){.vx-stream-kpis{grid-template-columns:1fr 1fr;gap:8px}.vx-stream-kpi{padding:12px}.vx-mini-grid{grid-template-columns:1fr}.vx-show-row{align-items:flex-start}.vx-show-stats{display:grid!important;grid-template-columns:1fr 1fr}.vx-card{border-radius:14px}}
</style>
<div class="vx-streams space-y-4">
 <div class="flex flex-wrap items-end justify-between gap-4"><div><h2 class="text-2xl font-bold text-gray-950 dark:text-white">Streams Overview</h2><p class="mt-1 text-sm text-gray-500">Shows, revenue, orders, shipments, and workflow for the selected period.</p></div><a href="{{ $this->showsUrl() }}" class="rounded-xl bg-primary-600 px-4 py-2.5 text-sm font-semibold text-white">View All Shows</a></div>

 <section class="vx-card p-4">
  <div class="flex flex-wrap items-end gap-3">
   <button wire:click="previousPeriod" class="rounded-lg border px-3 py-2 text-sm dark:border-gray-700">‹</button>
   <div class="min-w-[170px]"><label class="mb-1 block text-xs font-medium text-gray-500">Period</label><select wire:model.live="datePreset" class="w-full rounded-lg border-gray-300 bg-white text-sm dark:border-gray-600 dark:bg-gray-800"><option value="this_week">This week</option><option value="last_week">Last week</option><option value="this_month">This month</option><option value="last_month">Last month</option><option value="last_30">Last 30 days</option><option value="custom">Custom</option></select></div>
   <div><label class="mb-1 block text-xs font-medium text-gray-500">From</label><input type="date" wire:model.live="dateFrom" wire:change="$set('datePreset','custom')" class="rounded-lg border-gray-300 bg-white text-sm dark:border-gray-600 dark:bg-gray-800"></div>
   <div><label class="mb-1 block text-xs font-medium text-gray-500">To</label><input type="date" wire:model.live="dateTo" wire:change="$set('datePreset','custom')" class="rounded-lg border-gray-300 bg-white text-sm dark:border-gray-600 dark:bg-gray-800"></div>
   <button wire:click="nextPeriod" class="rounded-lg border px-3 py-2 text-sm dark:border-gray-700">›</button>
   <div class="ml-auto rounded-lg bg-gray-50 px-3 py-2 text-sm font-semibold dark:bg-gray-800">{{ $this->dateRangeLabel() }}</div>
  </div>
 </section>

 <div class="vx-stream-kpis">@foreach([['Shows',$s['shows'],'Selected period','heroicon-o-video-camera'],['Orders',number_format($s['orders']),'Imported orders','heroicon-o-shopping-cart'],['Shipments',number_format($s['shipments']),'Selected shows','heroicon-o-truck'],['Needs Submission',$s['needsSubmission'],'Requires follow-up','heroicon-o-exclamation-triangle'],['Gross Revenue','$'.number_format($s['grossRevenue'],0),'Whatnot Estimated Sales','heroicon-o-banknotes'],['Estimated Net Earnings','$'.number_format($s['netRevenue'],0),'Whatnot estimated earnings','heroicon-o-chart-bar-square']] as [$label,$value,$sub,$icon])<div class="vx-card vx-stream-kpi"><div class="flex items-center justify-between"><div class="text-xs font-medium text-gray-500">{{ $label }}</div><x-filament::icon :icon="$icon" class="h-5 w-5 text-primary-500" /></div><div class="mt-2 text-2xl font-bold">{{ $value }}</div><div class="mt-1 text-xs text-gray-400">{{ $sub }}</div></div>@endforeach</div>

 <div class="vx-mini-grid">
  <section class="vx-card p-5"><div class="flex items-center justify-between"><div><h3 class="font-bold">Upcoming Shows</h3><p class="mt-1 text-xs text-gray-500">Next scheduled shows, independent of the reporting period.</p></div></div>@forelse($this->upcomingShows as $show)<a href="{{ $this->showUrl($show->id) }}" class="vx-row"><div class="min-w-0 flex-1"><div class="truncate text-sm font-bold">{{ $show->title }}</div><div class="mt-1 text-xs text-gray-500">{{ $show->show_date?->format('M j, Y') }}{{ $show->start_time ? ' · '.$show->start_time->format('g:i A') : '' }} · {{ $show->streamers->pluck('name')->join(', ') ?: 'Unassigned' }}</div></div><span>›</span></a>@empty<div class="py-8 text-center text-sm text-gray-500">No upcoming shows scheduled.</div>@endforelse</section>
  <section class="vx-card p-5"><div><h3 class="font-bold">Needs Attention</h3><p class="mt-1 text-xs text-gray-500">Past shows in {{ $this->dateRangeLabel() }} waiting on submission.</p></div>@forelse($this->attentionShows as $show)<a href="{{ $this->showUrl($show->id) }}" class="vx-row"><div class="min-w-0 flex-1"><div class="truncate text-sm font-semibold">{{ $show->title }}</div><div class="text-xs text-gray-500">{{ $show->show_date?->format('M j') }} · {{ $show->streamers->pluck('name')->join(', ') ?: 'Unassigned' }}</div></div><span class="text-xs font-semibold text-amber-600">Submission ›</span></a>@empty<div class="py-8 text-center text-sm text-gray-500">Nothing waiting on submission.</div>@endforelse</section>
 </div>

 <div class="vx-stream-grid">
  <section class="vx-card p-5"><div class="flex items-center justify-between"><div><h3 class="font-bold">Shows in Period</h3><p class="mt-1 text-xs text-gray-500">{{ $this->dateRangeLabel() }}</p></div><a href="{{ $this->showsUrl() }}" class="text-xs font-semibold text-primary-600">Full list</a></div>@forelse($this->recentShows as $show)@php $log=$show->streamerLogEntry; @endphp<a href="{{ $this->showUrl($show->id) }}" class="vx-row vx-show-row"><div class="min-w-0 flex-1"><div class="truncate text-sm font-bold">{{ $show->title }}</div><div class="text-xs text-gray-500">{{ $show->show_date?->format('M j, Y') }} · {{ $show->streamers->pluck('name')->join(', ') ?: 'Unassigned' }}</div></div><div class="vx-show-stats flex shrink-0 gap-5 text-right text-xs"><div><div class="font-bold">${{ number_format((float)$show->gross_revenue,0) }}</div><div class="text-gray-400">Gross</div></div><div><div class="font-bold">${{ number_format((float)$show->whatnot_net,0) }}</div><div class="text-gray-400">Est. Net</div></div><div><div class="font-bold">{{ $show->orders_count }}</div><div class="text-gray-400">Orders</div></div><div><div class="font-bold">{{ $show->shipments_count }}</div><div class="text-gray-400">Shipments</div></div></div><span>›</span></a>@empty<div class="py-10 text-center text-sm text-gray-500">No completed shows in this period.</div>@endforelse</section>
  <aside class="space-y-4"><section class="vx-card p-5"><h3 class="font-bold">Recent Activity</h3>@forelse($this->recentActivity as $show)<a href="{{ $this->showUrl($show->id) }}" class="vx-row"><div class="min-w-0 flex-1"><div class="truncate text-sm font-semibold">{{ $show->title }}</div><div class="text-xs text-gray-500">{{ $show->show_date?->format('M j') }} · {{ \App\Models\Show::statusLabels()[$show->status] ?? ucfirst($show->status) }}</div></div></a>@empty<div class="py-8 text-center text-sm text-gray-500">No activity in this period.</div>@endforelse</section><section class="vx-card p-5"><h3 class="font-bold">Quick Links</h3><div class="mt-4 space-y-2"><a href="{{ $this->showsUrl() }}" class="vx-action"><div class="flex-1"><div class="text-sm font-semibold">All Shows</div><div class="text-xs text-gray-500">Open this period in list/calendar view</div></div><span>›</span></a><a href="{{ $this->shipmentsUrl() }}" class="vx-action"><div class="flex-1"><div class="text-sm font-semibold">Show Shipments</div><div class="text-xs text-gray-500">Track shipment progress</div></div><span>›</span></a></div></section></aside>
 </div>
</div>
</x-filament-panels::page>
