from pathlib import Path

p = Path('scripts/whatnot-scraper.cjs')
s = p.read_text()

needle = """  // Credentials are only required when we don't have a session cookie file\n  // and we're not in a mode that only tests cookies.\n  if (!hasCookieFile && !email && MODE !== 'cookie-test' && MODE !== 'dump-cookies' && MODE !== 'path-probe' && MODE !== 'api-discover') {\n"""
replacement = """  // dump-cookies is the credential-renewal path. It must never report a\n  // successful renewal unless credentials are actually available to establish\n  // (or confirm) an authenticated session first.\n  if (MODE === 'dump-cookies' && (!email || !password)) {\n    exitAfterStderr('Error: WHATNOT_EMAIL and WHATNOT_PASSWORD are required for credential renewal.\\n', 1);\n  }\n\n  // Credentials are only required when we don't have a session cookie file\n  // and we're not in a mode that only tests cookies.\n  if (!hasCookieFile && !email && MODE !== 'cookie-test' && MODE !== 'dump-cookies' && MODE !== 'path-probe' && MODE !== 'api-discover') {\n"""
if needle not in s:
    raise SystemExit('credential requirement anchor not found')
s = s.replace(needle, replacement, 1)

needle = """  try {\n    // If we have a cookie file, attempt a fast cookie-auth check before trying form login.\n    // This skips the Kasada-blocked login page entirely on subsequent runs.\n    if (hasCookieFile && MODE !== 'cookie-test' && MODE !== 'dump-cookies' && MODE !== 'path-probe' && MODE !== 'api-discover') {\n"""
replacement = """  try {\n    // Credential renewal used to skip performLogin entirely: dump-cookies was\n    // excluded from both auth branches below, so it simply dumped whatever\n    // stale cookies happened to be in the persistent profile and PHP called\n    // that a successful renewal. Make renewal establish/confirm auth first.\n    if (MODE === 'dump-cookies') {\n      info('dump-cookies: establishing authenticated session with configured credentials');\n      await performLogin(page, email, password);\n    }\n    // If we have a cookie file, attempt a fast cookie-auth check before trying form login.\n    // This skips the Kasada-blocked login page entirely on subsequent runs.\n    else if (hasCookieFile && MODE !== 'cookie-test' && MODE !== 'path-probe' && MODE !== 'api-discover') {\n"""
if needle not in s:
    raise SystemExit('auth branch anchor not found')
s = s.replace(needle, replacement, 1)

needle = """    // ── Mode: dump-cookies ────────────────────────────────────────────────────\n    // Dump the current Playwright context cookies for whatnot.com to stdout as JSON.\n    // Used after a successful login to persist the session.\n    if (MODE === 'dump-cookies') {\n      const cookies = await context.cookies('https://www.whatnot.com');\n      process.stdout.write(JSON.stringify(cookies, null, 2) + '\\n');\n      info('dump-cookies: dumped', cookies.length, 'cookies');\n      process.exit(0);\n    }\n"""
replacement = """    // ── Mode: dump-cookies ────────────────────────────────────────────────────\n    // Export only after performLogin above has established/confirmed auth. Save\n    // localStorage at the same moment so the next process restores one coherent\n    // session snapshot instead of cookies from now plus localStorage from an\n    // older run. Cookie values remain JSON-only on stdout; diagnostics log names\n    // and metadata only.\n    if (MODE === 'dump-cookies') {\n      const cookies = await context.cookies('https://www.whatnot.com');\n\n      try {\n        const ls = await page.evaluate(() => {\n          const out = {};\n          for (let i = 0; i < localStorage.length; i++) {\n            const k = localStorage.key(i);\n            out[k] = localStorage.getItem(k);\n          }\n          return out;\n        });\n        const lsFile = require('path').join(__dirname, '../storage/whatnot-localstorage.json');\n        require('fs').writeFileSync(lsFile, JSON.stringify(ls));\n        info('dump-cookies: saved localStorage (' + Object.keys(ls).length + ' keys) →', lsFile);\n      } catch (e) {\n        info('dump-cookies: localStorage save skipped:', e.message);\n      }\n\n      if (process.env.WHATNOT_BROWSER_DIAGNOSTICS === '1') {\n        const metadata = cookies.map((c) => ({\n          name: c.name,\n          domain: c.domain,\n          path: c.path,\n          expires: c.expires,\n          httpOnly: c.httpOnly,\n          secure: c.secure,\n          sameSite: c.sameSite,\n        }));\n        info('[browser-diag] dump-cookies metadata:', JSON.stringify(metadata));\n      }\n\n      info('dump-cookies: authenticated export contains', cookies.length, 'cookies');\n      // Let Chrome flush its persistent profile before exiting; process.exit()\n      // immediately after reading cookies could leave the on-disk profile behind\n      // the JSON snapshot we just returned.\n      await context.close().catch(() => {});\n      writeJsonAndExit(cookies);\n      return;\n    }\n"""
if needle not in s:
    raise SystemExit('dump-cookies block anchor not found')
s = s.replace(needle, replacement, 1)

p.write_text(s)
