'use strict';
const {app,BrowserWindow,ipcMain}=require('electron');const path=require('path'),fs=require('fs'),os=require('os'),{spawn}=require('child_process'),https=require('https');let win,child=null;
const dataDir=()=>path.join(app.getPath('userData'),'collector'), bundled=()=>app.isPackaged?path.join(process.resourcesPath,'collector'):path.join(__dirname,'..','collector');
function copyDir(s,d){fs.mkdirSync(d,{recursive:true});for(const e of fs.readdirSync(s,{withFileTypes:true})){const a=path.join(s,e.name),b=path.join(d,e.name);if(e.isDirectory())copyDir(a,b);else if(e.name!=='config.json')fs.copyFileSync(a,b)}}
function ensure(){const d=dataDir();fs.mkdirSync(d,{recursive:true});copyDir(bundled(),d);return d}
function cfg(){const d=ensure(),p=path.join(d,'config.json');if(!fs.existsSync(p)){const x=JSON.parse(fs.readFileSync(path.join(d,'config.example.json'),'utf8'));x.api_url='https://vortexops.tech/api';x.headless=false;fs.writeFileSync(p,JSON.stringify(x,null,2))}return{p,d,v:JSON.parse(fs.readFileSync(p,'utf8'))}}
function emit(s){win&&win.webContents.send('log',String(s))}
function detectChrome(){const a=[process.env.PROGRAMFILES&&path.join(process.env.PROGRAMFILES,'Google','Chrome','Application','chrome.exe'),process.env['PROGRAMFILES(X86)']&&path.join(process.env['PROGRAMFILES(X86)'],'Google','Chrome','Application','chrome.exe'),process.env.LOCALAPPDATA&&path.join(process.env.LOCALAPPDATA,'Google','Chrome','Application','chrome.exe')].filter(Boolean);return a.find(fs.existsSync)||''}
function run(cmd,args,cwd,env={}){return new Promise(res=>{if(child)return res({code:-1,error:'Already running'});child=spawn(cmd,args,{cwd,windowsHide:true,env:{...process.env,...env}});child.stdout.on('data',emit);child.stderr.on('data',emit);child.on('error',e=>{emit('ERROR: '+e.message);child=null;res({code:-1,error:e.message})});child.on('close',code=>{child=null;res({code})})})}
function launchChrome(){const c=cfg(),chrome=c.v.chrome_path&&fs.existsSync(c.v.chrome_path)?c.v.chrome_path:detectChrome();if(!chrome)return Promise.resolve({code:-1,error:'Google Chrome was not found.'});const profile=c.v.profile_dir?path.resolve(c.v.profile_dir):path.join(app.getPath('userData'),'ChromeProfile');fs.mkdirSync(profile,{recursive:true});emit('Opening Google Chrome for Whatnot login…');return new Promise(res=>{const p=spawn(chrome,[`--user-data-dir=${profile}`,'--no-first-run','--no-default-browser-check','https://www.whatnot.com/dashboard/home'],{detached:false,stdio:'ignore',windowsHide:false});p.on('error',e=>{emit('ERROR: '+e.message);res({code:-1,error:e.message})});p.on('close',code=>{const x=cfg();x.v.profile_dir=profile;x.v.chrome_path=chrome;fs.writeFileSync(x.p,JSON.stringify(x.v,null,2));emit('Whatnot Chrome closed. Login session saved.');res({code:code||0})})})}
app.whenReady().then(()=>{win=new BrowserWindow({width:960,height:760,minWidth:800,minHeight:640,backgroundColor:'#f7f8fb',webPreferences:{preload:path.join(__dirname,'preload.cjs')}});win.loadFile(path.join(__dirname,'index.html'))});
ipcMain.handle('state',()=>{const c=cfg();return{configured:!!c.v.api_token&&!String(c.v.api_token).includes('PASTE_'),apiUrl:c.v.api_url||'https://vortexops.tech/api',computer:os.hostname(),version:app.getVersion(),chrome:!!detectChrome()}});
ipcMain.handle('save-token',(_,t)=>{const c=cfg();c.v.api_url='https://vortexops.tech/api';c.v.api_token=String(t||'').trim();c.v.headless=false;fs.writeFileSync(c.p,JSON.stringify(c.v,null,2));return{ok:!!c.v.api_token}});
ipcMain.handle('login',()=>launchChrome());
ipcMain.handle('sync',()=>{const c=cfg();const exe=app.isPackaged?path.join(process.resourcesPath,'runtime','vortex-collector.exe'):'';if(app.isPackaged&&!fs.existsSync(exe))return{code:-1,error:'Bundled collector runtime is missing.'};return app.isPackaged?run(exe,[],c.d,{VORTEX_COLLECTOR_ROOT:c.d}):run('node',[path.join(c.d,'scrapling_collector.cjs')],c.d)});
ipcMain.handle('stop',()=>{if(child){child.kill();child=null;return true}return false});
